-- ============================================================
-- wnn_cert DDL (MySQL)
-- 벤더 MSSQL 테이블 기반 -> MySQL 변환, TW_ 접두사
-- ============================================================

-- 1. TW_USER - 사용자
DROP TABLE IF EXISTS TW_USER;
CREATE TABLE IF NOT EXISTS TW_USER (
    USER_ID VARCHAR(50) NOT NULL COMMENT '사용자ID',
    USER_NM VARCHAR(100) COMMENT '이름',
    USER_PW VARCHAR(200) COMMENT '비밀번호',
    DEPT_NM VARCHAR(100) COMMENT '부서',
    ROLE_CD VARCHAR(20) DEFAULT 'USER' COMMENT '역할(ADMIN/EVAL/USER)',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자';

-- 2. TW_TREE - 인증기준 트리 (from T_TREE)
DROP TABLE IF EXISTS TW_TREE;
CREATE TABLE IF NOT EXISTS TW_TREE (
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    TAB_ID VARCHAR(20) NOT NULL COMMENT '탭구분',
    GRP_CD VARCHAR(20) NOT NULL COMMENT '트리그룹',
    NODE_ID VARCHAR(20) NOT NULL COMMENT '노드ID',
    PARENT_ID VARCHAR(20) NOT NULL COMMENT '부모노드ID',
    NODE_NM VARCHAR(200) COMMENT '노드명',
    NODE_DESC TEXT COMMENT '설명',
    SORT_ORD INT DEFAULT 0 COMMENT '정렬순서',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    PRIMARY KEY (COMP_CD, TAB_ID, GRP_CD, NODE_ID, PARENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='인증기준 트리';

-- 3. TW_FORM_M - 완결도 서식 마스터 (from T_FORM_M)
DROP TABLE IF EXISTS TW_FORM_M;
CREATE TABLE IF NOT EXISTS TW_FORM_M (
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    FORM_CD VARCHAR(20) NOT NULL COMMENT '서식코드',
    FORM_NM VARCHAR(200) COMMENT '서식명',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    PRIMARY KEY (COMP_CD, FORM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='완결도 서식 마스터';

-- 4. TW_FORM_D - 완결도 서식 항목정의 (from T_FORM_D)
DROP TABLE IF EXISTS TW_FORM_D;
CREATE TABLE IF NOT EXISTS TW_FORM_D (
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    FORM_CD VARCHAR(20) NOT NULL COMMENT '서식코드',
    SEC_CD VARCHAR(10) NOT NULL COMMENT '섹션코드(COL1~COL6)',
    ITEM_SEQ INT NOT NULL COMMENT '항목순번',
    ITEM_NM VARCHAR(200) COMMENT '항목명',
    ITEM_DESC VARCHAR(500) COMMENT '항목설명',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    PRIMARY KEY (COMP_CD, FORM_CD, SEC_CD, ITEM_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='완결도 서식 항목정의';

-- 5. TW_FORM_RESULT - 완결도 평가결과 (from T_FORM_COMPLETE_4)
DROP TABLE IF EXISTS TW_FORM_RESULT;
CREATE TABLE IF NOT EXISTS TW_FORM_RESULT (
    RESULT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '결과ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DISCHARGE_DT VARCHAR(10) NOT NULL COMMENT '퇴원일자',
    PAT_CD VARCHAR(20) NOT NULL COMMENT '환자번호',
    EVAL_ROUND VARCHAR(20) NOT NULL COMMENT '차수(1차/2차)',
    FORM_CD VARCHAR(20) COMMENT '서식코드',
    SEC_CD VARCHAR(10) COMMENT '섹션코드',
    ITEM_SEQ INT COMMENT '항목순번',
    CHK_VAL VARCHAR(1) COMMENT '체크값(Y/N/1/0)',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(20) COMMENT '수정자',
    PRIMARY KEY (RESULT_ID),
    INDEX IDX_TW_FORM_RESULT_01 (COMP_CD, DISCHARGE_DT, PAT_CD, EVAL_ROUND)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='완결도 평가결과';

-- 6. TW_QPS - QPS 분류 (from T_QPS)
DROP TABLE IF EXISTS TW_QPS;
CREATE TABLE IF NOT EXISTS TW_QPS (
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    QPS_CD VARCHAR(20) NOT NULL COMMENT 'QPS코드',
    QPS_NM VARCHAR(100) COMMENT 'QPS명',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(20) COMMENT '수정자',
    PRIMARY KEY (COMP_CD, QPS_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='QPS 분류';

-- 7. TW_RPT - 환자안전 사고보고서 (from T_RPT)
DROP TABLE IF EXISTS TW_RPT;
CREATE TABLE IF NOT EXISTS TW_RPT (
    RPT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '보고서ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) COMMENT '환자ID',
    RPT_DT VARCHAR(10) NOT NULL COMMENT '보고일자',
    RPT_TYPE VARCHAR(50) COMMENT '보고유형(낙상/투약/기타)',
    RPT_TITLE VARCHAR(200) COMMENT '보고제목',
    RPT_CONTENT TEXT COMMENT '보고내용',
    ERR_GRADE VARCHAR(50) COMMENT '오류등급',
    OCCUR_DT VARCHAR(20) COMMENT '발생일시',
    OCCUR_PLACE VARCHAR(100) COMMENT '발생장소',
    ACTION_DESC TEXT COMMENT '조치내용',
    PREVENT_DESC TEXT COMMENT '재발방지대책',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(20) COMMENT '수정자',
    PRIMARY KEY (RPT_ID),
    INDEX IDX_TW_RPT_01 (COMP_CD, RPT_DT, RPT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='환자안전 사고보고서';

-- 8. TW_PATIENT_CNT - 재원환자 등록 (from T_PATIENTCNT)
DROP TABLE IF EXISTS TW_PATIENT_CNT;
CREATE TABLE IF NOT EXISTS TW_PATIENT_CNT (
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    CNT_TYPE VARCHAR(20) NOT NULL COMMENT '구분(01-총재원일/02-평균환자수)',
    CNT_YEAR VARCHAR(4) NOT NULL COMMENT '년도',
    M01 INT DEFAULT 0 COMMENT '1월',
    M02 INT DEFAULT 0 COMMENT '2월',
    M03 INT DEFAULT 0 COMMENT '3월',
    M04 INT DEFAULT 0 COMMENT '4월',
    M05 INT DEFAULT 0 COMMENT '5월',
    M06 INT DEFAULT 0 COMMENT '6월',
    M07 INT DEFAULT 0 COMMENT '7월',
    M08 INT DEFAULT 0 COMMENT '8월',
    M09 INT DEFAULT 0 COMMENT '9월',
    M10 INT DEFAULT 0 COMMENT '10월',
    M11 INT DEFAULT 0 COMMENT '11월',
    M12 INT DEFAULT 0 COMMENT '12월',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(20) COMMENT '수정자',
    PRIMARY KEY (COMP_CD, CNT_TYPE, CNT_YEAR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='재원환자 등록';

-- 9. TW_EVAL - 인증평가 마스터
DROP TABLE IF EXISTS TW_EVAL;
CREATE TABLE IF NOT EXISTS TW_EVAL (
    EVAL_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '평가ID',
    COMP_CD VARCHAR(10) COMMENT '회사구분',
    EVAL_YEAR VARCHAR(4) COMMENT '평가년도',
    EVAL_CYCLE VARCHAR(10) COMMENT '평가주기',
    EVAL_STATUS VARCHAR(20) DEFAULT '준비' COMMENT '상태(준비/진행/완료)',
    EVAL_RESULT VARCHAR(20) COMMENT '결과(인증/조건부/불인증)',
    START_DT DATE COMMENT '평가시작일',
    END_DT DATE COMMENT '평가종료일',
    TOTAL_SCORE DECIMAL(5,2) DEFAULT 0 COMMENT '총점',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(50) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(50) COMMENT '수정자',
    PRIMARY KEY (EVAL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='인증평가';

-- 10. TW_EVAL_DTL - 인증평가 상세
DROP TABLE IF EXISTS TW_EVAL_DTL;
CREATE TABLE IF NOT EXISTS TW_EVAL_DTL (
    DTL_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '상세ID',
    EVAL_ID BIGINT NOT NULL COMMENT '평가ID',
    NODE_ID VARCHAR(20) COMMENT '트리노드ID(항목)',
    SCORE DECIMAL(5,2) DEFAULT 0 COMMENT '점수',
    GRADE VARCHAR(10) COMMENT '등급(상/중/하)',
    EVIDENCE TEXT COMMENT '근거자료',
    NOTE TEXT COMMENT '비고',
    EVAL_USER VARCHAR(50) COMMENT '평가자',
    EVAL_DT DATETIME COMMENT '평가일시',
    PRIMARY KEY (DTL_ID),
    INDEX IDX_TW_EVAL_DTL_01 (EVAL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='인증평가 상세';

-- 11. TW_IMPROVE - 개선활동
DROP TABLE IF EXISTS TW_IMPROVE;
CREATE TABLE IF NOT EXISTS TW_IMPROVE (
    IMPROVE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '개선ID',
    DTL_ID BIGINT COMMENT '평가상세ID',
    TITLE VARCHAR(500) COMMENT '개선제목',
    CONTENT TEXT COMMENT '개선내용',
    IMP_STATUS VARCHAR(20) DEFAULT '계획' COMMENT '상태(계획/진행/완료)',
    DUE_DT DATE COMMENT '목표완료일',
    COMP_DT DATE COMMENT '실제완료일',
    MANAGER VARCHAR(50) COMMENT '담당자',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(50) COMMENT '등록자',
    PRIMARY KEY (IMPROVE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='개선활동';

-- 12. TW_REF - 레퍼런스 코드 (from T_REF)
DROP TABLE IF EXISTS TW_REF;
CREATE TABLE IF NOT EXISTS TW_REF (
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    REF_CD VARCHAR(50) NOT NULL COMMENT '참고코드',
    REF_SEQ INT NOT NULL COMMENT '순번',
    REF_VAL VARCHAR(100) COMMENT '값',
    NOTE VARCHAR(255) COMMENT '내용',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(20) COMMENT '수정자',
    PRIMARY KEY (COMP_CD, REF_CD, REF_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='레퍼런스 코드';

-- ============================================================
-- 추가 실무 테이블 (요양병원 인증 실무)
-- ============================================================

-- 13. TW_VACCIN - 예방접종 관리
DROP TABLE IF EXISTS TW_VACCIN;
CREATE TABLE IF NOT EXISTS TW_VACCIN (
    VACCIN_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '접종ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    VACCIN_YEAR VARCHAR(4) NOT NULL COMMENT '년도',
    VACCIN_TYPE VARCHAR(50) COMMENT '구분(독감/B형간염/코로나 등)',
    EMP_NM VARCHAR(50) COMMENT '직원명',
    DEPT_NM VARCHAR(50) COMMENT '부서',
    JOB_TYPE VARCHAR(50) COMMENT '직종',
    VACCIN_DT VARCHAR(10) COMMENT '접종일자',
    VACCIN_PLACE VARCHAR(20) COMMENT '원내/원외',
    DRUG_NM VARCHAR(100) COMMENT '약품명',
    LOT_NO VARCHAR(50) COMMENT 'LOT 번호',
    SIDE_EFFECT VARCHAR(200) COMMENT '이상반응',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (VACCIN_ID),
    INDEX IDX_TW_VACCIN_01 (COMP_CD, VACCIN_YEAR, VACCIN_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='예방접종 관리';

-- 14. TW_RESTRAINT - 격리/강박 기록지
DROP TABLE IF EXISTS TW_RESTRAINT;
CREATE TABLE IF NOT EXISTS TW_RESTRAINT (
    RESTRAINT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '기록ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) NOT NULL COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    RESTRAINT_TYPE VARCHAR(20) COMMENT '유형(격리/강박)',
    START_DT DATETIME COMMENT '시작일시',
    END_DT DATETIME COMMENT '종료일시',
    REASON TEXT COMMENT '사유',
    BODY_PART VARCHAR(100) COMMENT '적용부위(강박)',
    ORDER_DR VARCHAR(50) COMMENT '처방의사',
    NURSE_NM VARCHAR(50) COMMENT '수행간호사',
    MONITOR_INTERVAL VARCHAR(20) COMMENT '관찰간격',
    SKIN_STATUS VARCHAR(200) COMMENT '피부상태',
    CIRCULATION VARCHAR(200) COMMENT '순환상태',
    RELEASE_REASON VARCHAR(200) COMMENT '해제사유',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (RESTRAINT_ID),
    INDEX IDX_TW_RESTRAINT_01 (COMP_CD, PAT_CD, RESTRAINT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='격리/강박 기록';

-- 15. TW_FIRE_EQUIP - 소화기/소방설비 점검
DROP TABLE IF EXISTS TW_FIRE_EQUIP;
CREATE TABLE IF NOT EXISTS TW_FIRE_EQUIP (
    EQUIP_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '장비ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    CHK_YEAR VARCHAR(4) NOT NULL COMMENT '점검년도',
    BUILDING VARCHAR(50) COMMENT '건물/층',
    LOCATION VARCHAR(100) COMMENT '설치위치',
    EQUIP_TYPE VARCHAR(50) COMMENT '소화기 종류',
    M01 VARCHAR(20) COMMENT '1월점검',
    M02 VARCHAR(20) COMMENT '2월점검',
    M03 VARCHAR(20) COMMENT '3월점검',
    M04 VARCHAR(20) COMMENT '4월점검',
    M05 VARCHAR(20) COMMENT '5월점검',
    M06 VARCHAR(20) COMMENT '6월점검',
    M07 VARCHAR(20) COMMENT '7월점검',
    M08 VARCHAR(20) COMMENT '8월점검',
    M09 VARCHAR(20) COMMENT '9월점검',
    M10 VARCHAR(20) COMMENT '10월점검',
    M11 VARCHAR(20) COMMENT '11월점검',
    M12 VARCHAR(20) COMMENT '12월점검',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (EQUIP_ID),
    INDEX IDX_TW_FIRE_EQUIP_01 (COMP_CD, CHK_YEAR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='소화기/소방설비 점검';

-- 16. TW_STAFF_EDU - 직원 교육관리
DROP TABLE IF EXISTS TW_STAFF_EDU;
CREATE TABLE IF NOT EXISTS TW_STAFF_EDU (
    EDU_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '교육ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    EDU_YEAR VARCHAR(4) NOT NULL COMMENT '교육년도',
    EDU_TYPE VARCHAR(50) COMMENT '교육구분(필수/법정의무/특성화/기타)',
    EDU_TITLE VARCHAR(200) COMMENT '교육명',
    EDU_DT VARCHAR(10) COMMENT '교육일자',
    EDU_TIME VARCHAR(20) COMMENT '교육시간',
    INSTRUCTOR VARCHAR(50) COMMENT '강사명',
    EDU_METHOD VARCHAR(50) COMMENT '교육방법(집합/온라인/실습)',
    TARGET_DEPT VARCHAR(100) COMMENT '대상부서',
    TARGET_CNT INT DEFAULT 0 COMMENT '대상인원',
    ATTEND_CNT INT DEFAULT 0 COMMENT '참석인원',
    ATTEND_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '참석률',
    EDU_CONTENT TEXT COMMENT '교육내용',
    EVAL_RESULT VARCHAR(50) COMMENT '평가결과',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (EDU_ID),
    INDEX IDX_TW_STAFF_EDU_01 (COMP_CD, EDU_YEAR, EDU_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='직원 교육관리';

-- 17. TW_STAFF_EDU_ATT - 직원 교육 참석자
DROP TABLE IF EXISTS TW_STAFF_EDU_ATT;
CREATE TABLE IF NOT EXISTS TW_STAFF_EDU_ATT (
    ATT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '참석ID',
    EDU_ID BIGINT NOT NULL COMMENT '교육ID',
    EMP_NM VARCHAR(50) COMMENT '직원명',
    DEPT_NM VARCHAR(50) COMMENT '부서',
    JOB_TYPE VARCHAR(50) COMMENT '직종',
    ATTEND_YN CHAR(1) DEFAULT 'Y' COMMENT '참석여부',
    TEST_SCORE DECIMAL(5,2) COMMENT '시험점수',
    NOTE VARCHAR(200) COMMENT '비고',
    PRIMARY KEY (ATT_ID),
    INDEX IDX_TW_STAFF_EDU_ATT_01 (EDU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='직원 교육 참석자';

-- 18. TW_HEALTH_CHK - 직원 건강검진
DROP TABLE IF EXISTS TW_HEALTH_CHK;
CREATE TABLE IF NOT EXISTS TW_HEALTH_CHK (
    CHK_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '검진ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    EMP_NM VARCHAR(50) NOT NULL COMMENT '직원명',
    CHK_YEAR VARCHAR(4) NOT NULL COMMENT '년도',
    DEPT_NM VARCHAR(50) COMMENT '부서',
    JOB_TYPE VARCHAR(50) COMMENT '직종',
    HIRE_DT VARCHAR(10) COMMENT '입사일',
    -- 일반검진
    GENERAL_DT VARCHAR(10) COMMENT '일반검진일',
    GENERAL_RESULT VARCHAR(50) COMMENT '일반검진결과',
    GENERAL_FOLLOWUP VARCHAR(200) COMMENT '사후관리',
    -- 결핵검진
    TB_XRAY_DT VARCHAR(10) COMMENT '결핵(X-ray)일',
    TB_XRAY_RESULT VARCHAR(50) COMMENT '결핵결과',
    TB_LATENT_DT VARCHAR(10) COMMENT '잠복결핵검진일',
    TB_LATENT_RESULT VARCHAR(50) COMMENT '잠복결핵결과',
    TB_FOLLOWUP VARCHAR(200) COMMENT '결핵사후관리',
    -- B형간염
    HBV_DT VARCHAR(10) COMMENT 'B형간염검진일',
    HBV_ANTIGEN VARCHAR(20) COMMENT '항원',
    HBV_ANTIBODY VARCHAR(20) COMMENT '항체',
    HBV_FOLLOWUP VARCHAR(200) COMMENT 'B형간염사후관리',
    -- 독감예방접종
    FLU_DT VARCHAR(10) COMMENT '독감접종일',
    FLU_TYPE VARCHAR(20) COMMENT '접종구분',
    FLU_REASON VARCHAR(100) COMMENT '미접종사유',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (CHK_ID),
    INDEX IDX_TW_HEALTH_CHK_01 (COMP_CD, CHK_YEAR, EMP_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='직원 건강검진';

-- 19. TW_MED_DEVICE - 의료기기 관리
DROP TABLE IF EXISTS TW_MED_DEVICE;
CREATE TABLE IF NOT EXISTS TW_MED_DEVICE (
    DEVICE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '기기ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DEVICE_NO VARCHAR(50) COMMENT '장비번호',
    CATEGORY VARCHAR(50) COMMENT '품목분류명',
    SUB_CATEGORY VARCHAR(50) COMMENT '품목세분류명',
    SERIAL_NO VARCHAR(50) COMMENT '일련번호',
    DEVICE_NM VARCHAR(100) COMMENT '제품명',
    MODEL_NM VARCHAR(50) COMMENT '모델명',
    MAKER VARCHAR(50) COMMENT '제조회사',
    MAKE_DT VARCHAR(10) COMMENT '제조년월',
    MAKE_NO VARCHAR(50) COMMENT '제조번호',
    INSTALL_PLACE VARCHAR(100) COMMENT '설치장소',
    SUPPLIER VARCHAR(100) COMMENT '구입처',
    PURCHASE_DT VARCHAR(10) COMMENT '구입일자',
    INSPECT_CYCLE VARCHAR(20) COMMENT '점검주기',
    LAST_INSPECT_DT VARCHAR(10) COMMENT '최근점검일',
    NEXT_INSPECT_DT VARCHAR(10) COMMENT '차기점검일',
    DEVICE_STATUS VARCHAR(20) DEFAULT '정상' COMMENT '상태(정상/수리중/폐기)',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (DEVICE_ID),
    INDEX IDX_TW_MED_DEVICE_01 (COMP_CD, CATEGORY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='의료기기 관리';

-- 20. TW_STAFF_DUTY - 당직/인력 현황
DROP TABLE IF EXISTS TW_STAFF_DUTY;
CREATE TABLE IF NOT EXISTS TW_STAFF_DUTY (
    DUTY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '당직ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    WORK_DT VARCHAR(10) NOT NULL COMMENT '일자',
    PAT_CNT INT DEFAULT 0 COMMENT '입원환자수',
    DR_NEED INT DEFAULT 0 COMMENT '필요인력-의사',
    DR_ASSIGN INT DEFAULT 0 COMMENT '배치인력-의사',
    DR_PER_PAT DECIMAL(5,2) DEFAULT 0 COMMENT '의사당 환자수',
    NR_NEED INT DEFAULT 0 COMMENT '필요인력-간호사',
    NR_ASSIGN INT DEFAULT 0 COMMENT '배치인력-간호사',
    NR_PER_PAT DECIMAL(5,2) DEFAULT 0 COMMENT '간호사당 환자수',
    LEGAL_YN CHAR(1) COMMENT '법적기준 준수여부',
    DAY_DR VARCHAR(50) COMMENT '주간당직의사',
    NIGHT_DR VARCHAR(50) COMMENT '야간당직의사',
    DAY_NR VARCHAR(100) COMMENT '주간간호사',
    NIGHT_NR VARCHAR(100) COMMENT '야간간호사',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (DUTY_ID),
    INDEX IDX_TW_STAFF_DUTY_01 (COMP_CD, WORK_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='당직/인력 현황';

-- 21. TW_MEAL_ROUND - 배식 라운딩 일지
DROP TABLE IF EXISTS TW_MEAL_ROUND;
CREATE TABLE IF NOT EXISTS TW_MEAL_ROUND (
    ROUND_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '라운딩ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    ROUND_DT VARCHAR(10) NOT NULL COMMENT '라운딩일자',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    DIET_TYPE VARCHAR(50) COMMENT '식이종류',
    ROUND_CONTENT TEXT COMMENT '라운딩내용',
    ACTION_DESC TEXT COMMENT '조치사항',
    ROUNDER VARCHAR(50) COMMENT '라운딩수행자',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (ROUND_ID),
    INDEX IDX_TW_MEAL_ROUND_01 (COMP_CD, ROUND_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='배식 라운딩 일지';

-- 22. TW_DRUG_MANAGE - 약품 관리대장
DROP TABLE IF EXISTS TW_DRUG_MANAGE;
CREATE TABLE IF NOT EXISTS TW_DRUG_MANAGE (
    DRUG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '약품ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DRUG_CD VARCHAR(50) COMMENT '약품코드',
    DRUG_NM VARCHAR(200) COMMENT '약품명',
    DRUG_TYPE VARCHAR(50) COMMENT '약품유형(일반/마약류/향정/고위험)',
    UNIT VARCHAR(20) COMMENT '단위',
    STORAGE VARCHAR(50) COMMENT '보관장소',
    STORAGE_COND VARCHAR(50) COMMENT '보관조건(실온/냉장/차광)',
    STOCK_QTY INT DEFAULT 0 COMMENT '재고수량',
    MIN_QTY INT DEFAULT 0 COMMENT '최소재고',
    EXPIRE_DT VARCHAR(10) COMMENT '유효기한',
    SUPPLIER VARCHAR(100) COMMENT '공급업체',
    LAST_CHECK_DT VARCHAR(10) COMMENT '최근점검일',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (DRUG_ID),
    INDEX IDX_TW_DRUG_MANAGE_01 (COMP_CD, DRUG_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='약품 관리대장';

-- 23. TW_INFECTION - 감염감시 기록
DROP TABLE IF EXISTS TW_INFECTION;
CREATE TABLE IF NOT EXISTS TW_INFECTION (
    INFECT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '감염ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    INFECT_DT VARCHAR(10) NOT NULL COMMENT '발생일자',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    WARD_NM VARCHAR(50) COMMENT '병동',
    INFECT_TYPE VARCHAR(50) COMMENT '감염유형(요로감염/폐렴/피부감염/MRSA 등)',
    INFECT_SITE VARCHAR(50) COMMENT '감염부위',
    SPECIMEN VARCHAR(50) COMMENT '검체',
    ORGANISM VARCHAR(100) COMMENT '원인균',
    ANTIBIOTIC VARCHAR(200) COMMENT '항생제',
    ISOLATION_YN CHAR(1) COMMENT '격리여부',
    ISOLATION_TYPE VARCHAR(50) COMMENT '격리유형',
    RESULT VARCHAR(50) COMMENT '결과(치료중/완치/전원)',
    ACTION_DESC TEXT COMMENT '조치내용',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (INFECT_ID),
    INDEX IDX_TW_INFECTION_01 (COMP_CD, INFECT_DT, INFECT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='감염감시 기록';

-- 24. TW_HAND_HYGIENE - 손위생 모니터링
DROP TABLE IF EXISTS TW_HAND_HYGIENE;
CREATE TABLE IF NOT EXISTS TW_HAND_HYGIENE (
    HH_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '모니터링ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    MONITOR_DT VARCHAR(10) NOT NULL COMMENT '조사일자',
    MONITOR_MONTH VARCHAR(7) COMMENT '조사월(YYYY-MM)',
    WARD_NM VARCHAR(50) COMMENT '병동/부서',
    JOB_TYPE VARCHAR(50) COMMENT '직종(의사/간호사/간병인 등)',
    OBSERVE_CNT INT DEFAULT 0 COMMENT '관찰건수',
    COMPLY_CNT INT DEFAULT 0 COMMENT '수행건수',
    COMPLY_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '수행률(%)',
    MOMENT1 INT DEFAULT 0 COMMENT 'Moment1-환자접촉전',
    MOMENT2 INT DEFAULT 0 COMMENT 'Moment2-무균시술전',
    MOMENT3 INT DEFAULT 0 COMMENT 'Moment3-체액노출후',
    MOMENT4 INT DEFAULT 0 COMMENT 'Moment4-환자접촉후',
    MOMENT5 INT DEFAULT 0 COMMENT 'Moment5-환경접촉후',
    NOTE VARCHAR(255) COMMENT '비고',
    MONITOR_USER VARCHAR(50) COMMENT '조사자',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (HH_ID),
    INDEX IDX_TW_HAND_HYGIENE_01 (COMP_CD, MONITOR_MONTH, WARD_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='손위생 모니터링';

-- 25. TW_FILE - 첨부파일 관리 (규정/지침/서식 등 문서관리)
DROP TABLE IF EXISTS TW_FILE;
CREATE TABLE IF NOT EXISTS TW_FILE (
    FILE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '파일ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    REF_TYPE VARCHAR(20) NOT NULL COMMENT '참조유형(TREE/EDU/DEVICE/DRUG 등)',
    REF_ID VARCHAR(50) NOT NULL COMMENT '참조ID(노드ID/교육ID 등)',
    FILE_NM VARCHAR(200) NOT NULL COMMENT '원본파일명',
    SAVE_NM VARCHAR(200) NOT NULL COMMENT '저장파일명',
    FILE_PATH VARCHAR(500) COMMENT '파일경로',
    FILE_SIZE BIGINT DEFAULT 0 COMMENT '파일크기(byte)',
    FILE_EXT VARCHAR(20) COMMENT '확장자',
    FILE_TYPE VARCHAR(50) COMMENT '문서유형(규정/지침/서식/교육자료/기타)',
    FILE_VER VARCHAR(10) DEFAULT '1.0' COMMENT '버전',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (FILE_ID),
    INDEX IDX_TW_FILE_01 (COMP_CD, REF_TYPE, REF_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='첨부파일 관리';

-- 26. TW_FALL - 낙상 발생기록
DROP TABLE IF EXISTS TW_FALL;
CREATE TABLE IF NOT EXISTS TW_FALL (
    FALL_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '낙상ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    WARD_NM VARCHAR(50) COMMENT '병동',
    FALL_DT DATETIME COMMENT '발생일시',
    FALL_PLACE VARCHAR(100) COMMENT '발생장소',
    FALL_CAUSE VARCHAR(200) COMMENT '발생원인',
    INJURY_YN CHAR(1) COMMENT '손상여부',
    INJURY_DESC VARCHAR(500) COMMENT '손상내용',
    INJURY_GRADE VARCHAR(20) COMMENT '손상등급',
    ACTION_DESC TEXT COMMENT '조치내용',
    PREVENT_DESC TEXT COMMENT '재발방지대책',
    REPORT_USER VARCHAR(50) COMMENT '보고자',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (FALL_ID),
    INDEX IDX_TW_FALL_01 (COMP_CD, FALL_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='낙상 발생기록';

-- 27. TW_PRESSURE_ULCER - 욕창 발생기록
DROP TABLE IF EXISTS TW_PRESSURE_ULCER;
CREATE TABLE IF NOT EXISTS TW_PRESSURE_ULCER (
    PU_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '욕창ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    WARD_NM VARCHAR(50) COMMENT '병동',
    OCCUR_DT VARCHAR(10) COMMENT '발생일',
    OCCUR_TYPE VARCHAR(20) COMMENT '발생유형(원내발생/입원시)',
    PU_STAGE VARCHAR(20) COMMENT '욕창단계(1단계~4단계/미분류)',
    PU_SITE VARCHAR(100) COMMENT '발생부위',
    PU_SIZE VARCHAR(50) COMMENT '크기(cm)',
    TREATMENT TEXT COMMENT '치료내용',
    HEAL_DT VARCHAR(10) COMMENT '치유일',
    RESULT VARCHAR(20) COMMENT '결과(치유/진행중/전원)',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (PU_ID),
    INDEX IDX_TW_PU_01 (COMP_CD, OCCUR_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='욕창 발생기록';

-- 28. TW_CONSENT - 동의서 관리
DROP TABLE IF EXISTS TW_CONSENT;
CREATE TABLE IF NOT EXISTS TW_CONSENT (
    CONSENT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '동의서ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    CONSENT_TYPE VARCHAR(50) COMMENT '동의서유형(입원/수술/시술/수혈/DNR 등)',
    CONSENT_DT VARCHAR(10) COMMENT '동의일자',
    EXPLAIN_DR VARCHAR(50) COMMENT '설명의사',
    SIGNER VARCHAR(50) COMMENT '동의권자(본인/보호자)',
    SIGNER_REL VARCHAR(20) COMMENT '관계',
    COMPLETE_YN CHAR(1) COMMENT '완료여부',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (CONSENT_ID),
    INDEX IDX_TW_CONSENT_01 (COMP_CD, PAT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='동의서 관리';

-- 29. TW_SAFETY_ROUND - 안전 라운딩 (시설/환경 점검)
DROP TABLE IF EXISTS TW_SAFETY_ROUND;
CREATE TABLE IF NOT EXISTS TW_SAFETY_ROUND (
    ROUND_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '라운딩ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    ROUND_DT VARCHAR(10) NOT NULL COMMENT '점검일자',
    ROUND_TYPE VARCHAR(50) COMMENT '점검유형(시설환경/감염/안전)',
    ROUND_AREA VARCHAR(100) COMMENT '점검구역',
    CHK_ITEMS TEXT COMMENT '점검항목/결과(JSON)',
    GOOD_CNT INT DEFAULT 0 COMMENT '양호건수',
    BAD_CNT INT DEFAULT 0 COMMENT '불량건수',
    IMPROVE_DESC TEXT COMMENT '개선필요사항',
    ROUNDER VARCHAR(50) COMMENT '점검자',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (ROUND_ID),
    INDEX IDX_TW_SAFETY_ROUND_01 (COMP_CD, ROUND_DT, ROUND_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='안전 라운딩';

-- 30. TW_STERILIZE - 소독/멸균 관리
DROP TABLE IF EXISTS TW_STERILIZE;
CREATE TABLE IF NOT EXISTS TW_STERILIZE (
    STER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '소독ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    STER_DT VARCHAR(10) NOT NULL COMMENT '소독일자',
    STER_TYPE VARCHAR(50) COMMENT '유형(소독/멸균)',
    STER_METHOD VARCHAR(50) COMMENT '방법(EO가스/고압증기/화학소독 등)',
    TARGET_ITEM VARCHAR(200) COMMENT '대상물품',
    STER_QTY INT DEFAULT 0 COMMENT '수량',
    INDICATOR_RESULT VARCHAR(50) COMMENT '지시제 결과(합격/불합격)',
    WORKER VARCHAR(50) COMMENT '수행자',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (STER_ID),
    INDEX IDX_TW_STERILIZE_01 (COMP_CD, STER_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='소독/멸균 관리';

-- 31. TW_LAUNDRY - 세탁물 관리
DROP TABLE IF EXISTS TW_LAUNDRY;
CREATE TABLE IF NOT EXISTS TW_LAUNDRY (
    LAUNDRY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '세탁ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    LAUNDRY_DT VARCHAR(10) NOT NULL COMMENT '세탁일자',
    LAUNDRY_TYPE VARCHAR(50) COMMENT '구분(일반/감염)',
    WARD_NM VARCHAR(50) COMMENT '병동',
    ITEM_NM VARCHAR(200) COMMENT '세탁물 종류',
    SEND_QTY INT DEFAULT 0 COMMENT '발송수량',
    RECV_QTY INT DEFAULT 0 COMMENT '수령수량',
    CHK_RESULT VARCHAR(50) COMMENT '점검결과(양호/불량)',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (LAUNDRY_ID),
    INDEX IDX_TW_LAUNDRY_01 (COMP_CD, LAUNDRY_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='세탁물 관리';

-- 32. TW_WASTE - 폐기물 관리
DROP TABLE IF EXISTS TW_WASTE;
CREATE TABLE IF NOT EXISTS TW_WASTE (
    WASTE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '폐기물ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    WASTE_DT VARCHAR(10) NOT NULL COMMENT '처리일자',
    WASTE_TYPE VARCHAR(50) COMMENT '유형(의료폐기물/일반폐기물/감염폐기물)',
    WASTE_QTY DECIMAL(10,2) DEFAULT 0 COMMENT '수량(kg)',
    HANDLER VARCHAR(100) COMMENT '처리업체',
    STORAGE_PLACE VARCHAR(100) COMMENT '보관장소',
    CHK_RESULT VARCHAR(50) COMMENT '점검결과',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (WASTE_ID),
    INDEX IDX_TW_WASTE_01 (COMP_CD, WASTE_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='폐기물 관리';

-- 33. TW_DISCHARGE - 퇴원환자 관리
DROP TABLE IF EXISTS TW_DISCHARGE;
CREATE TABLE IF NOT EXISTS TW_DISCHARGE (
    DISCH_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '퇴원ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) NOT NULL COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    ADMIT_DT VARCHAR(10) COMMENT '입원일',
    DISCH_DT VARCHAR(10) COMMENT '퇴원일',
    DISCH_TYPE VARCHAR(20) COMMENT '퇴원유형(퇴원/전원/사망)',
    DIAG_NM VARCHAR(200) COMMENT '진단명',
    DISCH_PLAN TEXT COMMENT '퇴원계획',
    FOLLOWUP_PLAN TEXT COMMENT '추후관리계획',
    HOME_RETURN_YN CHAR(1) COMMENT '재택복귀여부',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (DISCH_ID),
    INDEX IDX_TW_DISCHARGE_01 (COMP_CD, DISCH_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='퇴원환자 관리';

-- 34. TW_COMMITTEE - 위원회 활동
DROP TABLE IF EXISTS TW_COMMITTEE;
CREATE TABLE IF NOT EXISTS TW_COMMITTEE (
    COMM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '활동ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    COMM_TYPE VARCHAR(50) COMMENT '위원회유형(감염관리/QI/윤리/약사 등)',
    MEETING_DT VARCHAR(10) COMMENT '회의일자',
    MEETING_TITLE VARCHAR(200) COMMENT '회의제목',
    ATTENDEES TEXT COMMENT '참석자',
    AGENDA TEXT COMMENT '안건',
    DECISION TEXT COMMENT '결정사항',
    ACTION_PLAN TEXT COMMENT '실행계획',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (COMM_ID),
    INDEX IDX_TW_COMMITTEE_01 (COMP_CD, COMM_TYPE, MEETING_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='위원회 활동';

-- 35. TW_PAIN_ASSESS - 통증 평가
DROP TABLE IF EXISTS TW_PAIN_ASSESS;
CREATE TABLE IF NOT EXISTS TW_PAIN_ASSESS (
    PAIN_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '통증ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    ASSESS_DT DATETIME COMMENT '평가일시',
    PAIN_SCORE INT COMMENT '통증점수(0~10 NRS)',
    PAIN_SITE VARCHAR(100) COMMENT '통증부위',
    PAIN_TYPE VARCHAR(50) COMMENT '통증유형(급성/만성/암성)',
    INTERVENTION VARCHAR(500) COMMENT '중재내용',
    RE_ASSESS_DT DATETIME COMMENT '재평가일시',
    RE_PAIN_SCORE INT COMMENT '재평가점수',
    ASSESSOR VARCHAR(50) COMMENT '평가자',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (PAIN_ID),
    INDEX IDX_TW_PAIN_01 (COMP_CD, PAT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='통증 평가';

-- 36. TW_NUTRITION - 영양 평가/관리
DROP TABLE IF EXISTS TW_NUTRITION;
CREATE TABLE IF NOT EXISTS TW_NUTRITION (
    NUTR_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '영양ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    ASSESS_DT VARCHAR(10) COMMENT '평가일',
    SCREEN_TOOL VARCHAR(50) COMMENT '선별도구(MNA/MUST/NRS-2002)',
    SCREEN_SCORE DECIMAL(5,2) COMMENT '선별점수',
    RISK_LEVEL VARCHAR(20) COMMENT '위험도(정상/저위험/고위험)',
    DIET_TYPE VARCHAR(50) COMMENT '식이유형',
    NUTR_PLAN TEXT COMMENT '영양관리계획',
    COUNSELING_DT VARCHAR(10) COMMENT '영양상담일',
    COUNSELOR VARCHAR(50) COMMENT '영양사',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (NUTR_ID),
    INDEX IDX_TW_NUTRITION_01 (COMP_CD, PAT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='영양 평가/관리';

-- 37. TW_REHAB - 재활치료 기록
DROP TABLE IF EXISTS TW_REHAB;
CREATE TABLE IF NOT EXISTS TW_REHAB (
    REHAB_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '재활ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    REHAB_DT VARCHAR(10) COMMENT '치료일',
    REHAB_TYPE VARCHAR(50) COMMENT '치료유형(물리/작업/언어/인지)',
    THERAPIST VARCHAR(50) COMMENT '치료사',
    TREAT_TIME INT COMMENT '치료시간(분)',
    TREAT_CONTENT TEXT COMMENT '치료내용',
    GOAL TEXT COMMENT '치료목표',
    PROGRESS VARCHAR(200) COMMENT '진행상황',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (REHAB_ID),
    INDEX IDX_TW_REHAB_01 (COMP_CD, PAT_CD, REHAB_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='재활치료 기록';

-- 38. TW_CPR_DRILL - CPR/응급 훈련
DROP TABLE IF EXISTS TW_CPR_DRILL;
CREATE TABLE IF NOT EXISTS TW_CPR_DRILL (
    DRILL_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '훈련ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DRILL_DT VARCHAR(10) COMMENT '훈련일자',
    DRILL_TYPE VARCHAR(50) COMMENT '훈련유형(CPR/소방/재난/코드블루)',
    DRILL_TITLE VARCHAR(200) COMMENT '훈련명',
    SCENARIO TEXT COMMENT '시나리오',
    PARTICIPANT_CNT INT DEFAULT 0 COMMENT '참여인원',
    RESULT TEXT COMMENT '훈련결과',
    IMPROVE_DESC TEXT COMMENT '개선사항',
    TRAINER VARCHAR(50) COMMENT '훈련지도자',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (DRILL_ID),
    INDEX IDX_TW_CPR_DRILL_01 (COMP_CD, DRILL_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CPR/응급 훈련';

-- 39. TW_WATER_QUALITY - 수질 검사
DROP TABLE IF EXISTS TW_WATER_QUALITY;
CREATE TABLE IF NOT EXISTS TW_WATER_QUALITY (
    WQ_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '검사ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    CHK_DT VARCHAR(10) COMMENT '검사일',
    CHK_POINT VARCHAR(100) COMMENT '검사지점',
    CHK_TYPE VARCHAR(50) COMMENT '검사유형(음용수/냉각탑/저수조)',
    LEGIONELLA VARCHAR(50) COMMENT '레지오넬라 결과',
    COLIFORM VARCHAR(50) COMMENT '대장균 결과',
    RESIDUAL_CL VARCHAR(50) COMMENT '잔류염소',
    TURBIDITY VARCHAR(50) COMMENT '탁도',
    PH VARCHAR(20) COMMENT 'pH',
    RESULT VARCHAR(20) COMMENT '판정(적합/부적합)',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (WQ_ID),
    INDEX IDX_TW_WQ_01 (COMP_CD, CHK_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='수질 검사';

-- 40. TW_COMPLAINT - 고충/민원 관리
DROP TABLE IF EXISTS TW_COMPLAINT;
CREATE TABLE IF NOT EXISTS TW_COMPLAINT (
    COMP_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '민원ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    RECV_DT VARCHAR(10) COMMENT '접수일',
    COMP_TYPE VARCHAR(50) COMMENT '유형(불만/건의/칭찬/기타)',
    COMP_CHANNEL VARCHAR(50) COMMENT '접수경로(대면/전화/서면/온라인)',
    COMP_TITLE VARCHAR(200) COMMENT '제목',
    COMP_CONTENT TEXT COMMENT '내용',
    COMP_DEPT VARCHAR(50) COMMENT '관련부서',
    HANDLER VARCHAR(50) COMMENT '처리담당자',
    ACTION_DESC TEXT COMMENT '처리내용',
    ACTION_DT VARCHAR(10) COMMENT '처리일',
    COMP_STATUS VARCHAR(20) DEFAULT '접수' COMMENT '상태(접수/처리중/완료)',
    SATISFACTION VARCHAR(20) COMMENT '만족도',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (COMP_ID),
    INDEX IDX_TW_COMPLAINT_01 (COMP_CD, RECV_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='고충/민원 관리';

-- ============================================================
-- 추가 테이블 (업체 테이블 기반 누락분)
-- ============================================================

-- 41. TW_COMPANY - 병원 기본정보 (from T_COMPANY_INFO)
DROP TABLE IF EXISTS TW_COMPANY;
CREATE TABLE IF NOT EXISTS TW_COMPANY (
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    COMP_NM VARCHAR(100) COMMENT '병원명',
    COMP_TYPE VARCHAR(50) COMMENT '병원유형(요양병원/정신병원/재활병원)',
    OWNER_NM VARCHAR(50) COMMENT '대표자',
    BIZ_NO VARCHAR(20) COMMENT '사업자번호',
    CORP_NO VARCHAR(20) COMMENT '법인번호',
    ZIP_CD VARCHAR(10) COMMENT '우편번호',
    ADDR VARCHAR(200) COMMENT '주소',
    ADDR_DTL VARCHAR(200) COMMENT '상세주소',
    TEL_NO VARCHAR(20) COMMENT '전화번호',
    FAX_NO VARCHAR(20) COMMENT '팩스번호',
    BED_CNT INT DEFAULT 0 COMMENT '허가병상수',
    OPEN_DT VARCHAR(10) COMMENT '개설일',
    CERT_STATUS VARCHAR(20) COMMENT '인증상태(인증/조건부/미인증)',
    CERT_DT VARCHAR(10) COMMENT '인증일',
    CERT_EXPIRE_DT VARCHAR(10) COMMENT '인증만료일',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(20) COMMENT '수정자',
    PRIMARY KEY (COMP_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='병원 기본정보';

-- 42. TW_STAFF - 직원 마스터 (from T_MEMBER_M)
DROP TABLE IF EXISTS TW_STAFF;
CREATE TABLE IF NOT EXISTS TW_STAFF (
    STAFF_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '직원ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    EMP_NO VARCHAR(20) COMMENT '사번',
    EMP_NM VARCHAR(50) NOT NULL COMMENT '직원명',
    DEPT_CD VARCHAR(20) COMMENT '부서코드',
    DEPT_NM VARCHAR(50) COMMENT '부서명',
    JOB_TYPE VARCHAR(50) COMMENT '직종(의사/간호사/약사/치료사/영양사/행정/간병인 등)',
    POSITION VARCHAR(50) COMMENT '직위',
    LICENSE_NO VARCHAR(50) COMMENT '면허번호',
    LICENSE_TYPE VARCHAR(50) COMMENT '면허유형',
    HIRE_DT VARCHAR(10) COMMENT '입사일',
    RESIGN_DT VARCHAR(10) COMMENT '퇴사일',
    BIRTH_DT VARCHAR(10) COMMENT '생년월일',
    GENDER VARCHAR(5) COMMENT '성별(M/F)',
    PHONE VARCHAR(20) COMMENT '연락처',
    EMAIL VARCHAR(100) COMMENT '이메일',
    STATUS VARCHAR(20) DEFAULT '재직' COMMENT '상태(재직/휴직/퇴직)',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(20) COMMENT '수정자',
    PRIMARY KEY (STAFF_ID),
    INDEX IDX_TW_STAFF_01 (COMP_CD, EMP_NM),
    INDEX IDX_TW_STAFF_02 (COMP_CD, DEPT_CD, JOB_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='직원 마스터';

-- 43. TW_STAFF_HIST - 직원 이력 (from T_MEMBER_H)
DROP TABLE IF EXISTS TW_STAFF_HIST;
CREATE TABLE IF NOT EXISTS TW_STAFF_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '이력ID',
    STAFF_ID BIGINT NOT NULL COMMENT '직원ID',
    HIST_TYPE VARCHAR(50) COMMENT '이력유형(입사/퇴사/승진/부서이동/면허갱신 등)',
    HIST_DT VARCHAR(10) COMMENT '이력일자',
    BEFORE_VAL VARCHAR(200) COMMENT '변경전',
    AFTER_VAL VARCHAR(200) COMMENT '변경후',
    NOTE VARCHAR(500) COMMENT '비고',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (HIST_ID),
    INDEX IDX_TW_STAFF_HIST_01 (STAFF_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='직원 이력';

-- 44. TW_RETURN_HOME - 재택복귀율 (from T_RETURNHOME)
DROP TABLE IF EXISTS TW_RETURN_HOME;
CREATE TABLE IF NOT EXISTS TW_RETURN_HOME (
    RH_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '복귀ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    STAT_YEAR VARCHAR(4) NOT NULL COMMENT '통계년도',
    STAT_MONTH VARCHAR(2) NOT NULL COMMENT '통계월',
    DISCH_CNT INT DEFAULT 0 COMMENT '퇴원환자수',
    HOME_CNT INT DEFAULT 0 COMMENT '재택복귀수',
    HOME_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '재택복귀율(%)',
    READMIT_CNT INT DEFAULT 0 COMMENT '재입원수',
    READMIT_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '재입원율(%)',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (RH_ID),
    UNIQUE INDEX IDX_TW_RH_01 (COMP_CD, STAT_YEAR, STAT_MONTH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='재택복귀율';

-- 45. TW_TAT - TAT 관리 (from T_TAT - 검체/영상 보고시간)
DROP TABLE IF EXISTS TW_TAT;
CREATE TABLE IF NOT EXISTS TW_TAT (
    TAT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'TAT_ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    TAT_TYPE VARCHAR(20) NOT NULL COMMENT '유형(검체/영상)',
    TAT_DT VARCHAR(10) NOT NULL COMMENT '검사일',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    TEST_NM VARCHAR(100) COMMENT '검사명',
    ORDER_DT DATETIME COMMENT '처방일시',
    COLLECT_DT DATETIME COMMENT '접수(채취)일시',
    REPORT_DT DATETIME COMMENT '보고일시',
    TAT_MIN INT COMMENT 'TAT(분)',
    GOAL_MIN INT COMMENT '목표TAT(분)',
    ACHIEVE_YN CHAR(1) COMMENT '달성여부',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (TAT_ID),
    INDEX IDX_TW_TAT_01 (COMP_CD, TAT_TYPE, TAT_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='TAT 관리';

-- 46. TW_RESTRAINT_LOG - 격리/강박 시행일지 (from T_COMPULSION 상세)
DROP TABLE IF EXISTS TW_RESTRAINT_LOG;
CREATE TABLE IF NOT EXISTS TW_RESTRAINT_LOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '일지ID',
    RESTRAINT_ID BIGINT NOT NULL COMMENT '격리강박ID',
    LOG_DT DATETIME NOT NULL COMMENT '관찰일시',
    VITAL_SIGN VARCHAR(100) COMMENT '활력징후',
    SKIN_STATUS VARCHAR(100) COMMENT '피부상태',
    CIRCULATION VARCHAR(100) COMMENT '말초순환',
    CONSCIOUSNESS VARCHAR(50) COMMENT '의식상태',
    BEHAVIOR VARCHAR(200) COMMENT '행동양상',
    FOOD_INTAKE VARCHAR(100) COMMENT '음식섭취',
    EXCRETION VARCHAR(100) COMMENT '배설',
    OBSERVER VARCHAR(50) COMMENT '관찰자',
    NOTE VARCHAR(500) COMMENT '비고',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (LOG_ID),
    INDEX IDX_TW_RESTRAINT_LOG_01 (RESTRAINT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='격리/강박 시행일지';

-- 47. TW_SIGN - 서명 관리 (from T_SIGNATURE)
DROP TABLE IF EXISTS TW_SIGN;
CREATE TABLE IF NOT EXISTS TW_SIGN (
    SIGN_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '서명ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    SIGN_TYPE VARCHAR(50) COMMENT '서명유형(문서승인/차트서명/교육확인)',
    REF_TYPE VARCHAR(20) COMMENT '참조유형',
    REF_ID VARCHAR(50) COMMENT '참조ID',
    SIGNER VARCHAR(50) COMMENT '서명자',
    SIGN_DT DATETIME COMMENT '서명일시',
    SIGN_STATUS VARCHAR(20) DEFAULT '대기' COMMENT '상태(대기/승인/반려)',
    REJECT_REASON VARCHAR(500) COMMENT '반려사유',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (SIGN_ID),
    INDEX IDX_TW_SIGN_01 (COMP_CD, REF_TYPE, REF_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='서명 관리';

-- 48. TW_SIGN_LINE - 결재선 (from T_SIGNLINE)
DROP TABLE IF EXISTS TW_SIGN_LINE;
CREATE TABLE IF NOT EXISTS TW_SIGN_LINE (
    LINE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '결재선ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    LINE_NM VARCHAR(100) COMMENT '결재선명',
    DOC_TYPE VARCHAR(50) COMMENT '문서유형',
    STEP_SEQ INT NOT NULL COMMENT '결재순서',
    APPROVER VARCHAR(50) COMMENT '결재자',
    APPROVER_ROLE VARCHAR(50) COMMENT '결재자역할',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (LINE_ID),
    INDEX IDX_TW_SIGN_LINE_01 (COMP_CD, DOC_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='결재선';

-- 49. TW_MENU_AUTH - 메뉴 권한 (from T_MENUPOWER)
DROP TABLE IF EXISTS TW_MENU_AUTH;
CREATE TABLE IF NOT EXISTS TW_MENU_AUTH (
    AUTH_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '권한ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    ROLE_CD VARCHAR(20) NOT NULL COMMENT '역할코드',
    MENU_CD VARCHAR(50) NOT NULL COMMENT '메뉴코드',
    READ_YN CHAR(1) DEFAULT 'Y' COMMENT '조회권한',
    WRITE_YN CHAR(1) DEFAULT 'N' COMMENT '등록/수정권한',
    DELETE_YN CHAR(1) DEFAULT 'N' COMMENT '삭제권한',
    PRINT_YN CHAR(1) DEFAULT 'N' COMMENT '출력권한',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (AUTH_ID),
    UNIQUE INDEX IDX_TW_MENU_AUTH_01 (COMP_CD, ROLE_CD, MENU_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='메뉴 권한';

-- 50. TW_DUTY_SCHEDULE - 근무표 (from T_DUTY)
DROP TABLE IF EXISTS TW_DUTY_SCHEDULE;
CREATE TABLE IF NOT EXISTS TW_DUTY_SCHEDULE (
    SCHED_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '스케줄ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DEPT_CD VARCHAR(20) COMMENT '부서코드',
    DEPT_NM VARCHAR(50) COMMENT '부서명',
    EMP_NM VARCHAR(50) COMMENT '직원명',
    SCHED_MONTH VARCHAR(7) NOT NULL COMMENT '근무월(YYYY-MM)',
    D01 VARCHAR(10) COMMENT '1일', D02 VARCHAR(10) COMMENT '2일',
    D03 VARCHAR(10) COMMENT '3일', D04 VARCHAR(10) COMMENT '4일',
    D05 VARCHAR(10) COMMENT '5일', D06 VARCHAR(10) COMMENT '6일',
    D07 VARCHAR(10) COMMENT '7일', D08 VARCHAR(10) COMMENT '8일',
    D09 VARCHAR(10) COMMENT '9일', D10 VARCHAR(10) COMMENT '10일',
    D11 VARCHAR(10) COMMENT '11일', D12 VARCHAR(10) COMMENT '12일',
    D13 VARCHAR(10) COMMENT '13일', D14 VARCHAR(10) COMMENT '14일',
    D15 VARCHAR(10) COMMENT '15일', D16 VARCHAR(10) COMMENT '16일',
    D17 VARCHAR(10) COMMENT '17일', D18 VARCHAR(10) COMMENT '18일',
    D19 VARCHAR(10) COMMENT '19일', D20 VARCHAR(10) COMMENT '20일',
    D21 VARCHAR(10) COMMENT '21일', D22 VARCHAR(10) COMMENT '22일',
    D23 VARCHAR(10) COMMENT '23일', D24 VARCHAR(10) COMMENT '24일',
    D25 VARCHAR(10) COMMENT '25일', D26 VARCHAR(10) COMMENT '26일',
    D27 VARCHAR(10) COMMENT '27일', D28 VARCHAR(10) COMMENT '28일',
    D29 VARCHAR(10) COMMENT '29일', D30 VARCHAR(10) COMMENT '30일',
    D31 VARCHAR(10) COMMENT '31일',
    DAY_CNT INT DEFAULT 0 COMMENT 'D근무일수',
    EVE_CNT INT DEFAULT 0 COMMENT 'E근무일수',
    NIGHT_CNT INT DEFAULT 0 COMMENT 'N근무일수',
    OFF_CNT INT DEFAULT 0 COMMENT '휴무일수',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (SCHED_ID),
    INDEX IDX_TW_DUTY_01 (COMP_CD, SCHED_MONTH, DEPT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='근무표';

-- 51. TW_INF_INSPECT - 감염 점검 (from T_INF_INSPECT)
DROP TABLE IF EXISTS TW_INF_INSPECT;
CREATE TABLE IF NOT EXISTS TW_INF_INSPECT (
    INSPECT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '점검ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    INSPECT_DT VARCHAR(10) NOT NULL COMMENT '점검일',
    INSPECT_TYPE VARCHAR(50) COMMENT '점검유형(환경소독/장비소독/린넨관리/손위생물품)',
    INSPECT_AREA VARCHAR(100) COMMENT '점검구역',
    CHK_ITEMS TEXT COMMENT '점검항목(JSON)',
    PASS_CNT INT DEFAULT 0 COMMENT '적합건수',
    FAIL_CNT INT DEFAULT 0 COMMENT '부적합건수',
    COMPLY_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '적합률(%)',
    IMPROVE_DESC TEXT COMMENT '개선사항',
    INSPECTOR VARCHAR(50) COMMENT '점검자',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    PRIMARY KEY (INSPECT_ID),
    INDEX IDX_TW_INF_INSPECT_01 (COMP_CD, INSPECT_DT, INSPECT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='감염 점검';

-- 52. TW_TEMPLATE - 문서 템플릿 (from T_TEMPLATE)
DROP TABLE IF EXISTS TW_TEMPLATE;
CREATE TABLE IF NOT EXISTS TW_TEMPLATE (
    TMPL_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '템플릿ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    TMPL_TYPE VARCHAR(50) COMMENT '유형(규정/지침/서식/교육자료)',
    TMPL_NM VARCHAR(200) COMMENT '템플릿명',
    TMPL_CONTENT LONGTEXT COMMENT '템플릿내용(HTML)',
    FILE_PATH VARCHAR(500) COMMENT '파일경로',
    VER VARCHAR(10) DEFAULT '1.0' COMMENT '버전',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(20) COMMENT '수정자',
    PRIMARY KEY (TMPL_ID),
    INDEX IDX_TW_TEMPLATE_01 (COMP_CD, TMPL_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='문서 템플릿';

-- 53. TW_NOTICE - 공지사항/게시판
DROP TABLE IF EXISTS TW_NOTICE;
CREATE TABLE IF NOT EXISTS TW_NOTICE (
    NOTICE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '게시글ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    BOARD_TYPE VARCHAR(20) DEFAULT 'NOTICE' COMMENT '게시판유형(NOTICE/QNA/DATA)',
    TITLE VARCHAR(200) NOT NULL COMMENT '제목',
    CONTENT LONGTEXT COMMENT '내용',
    WRITER VARCHAR(50) COMMENT '작성자',
    VIEW_CNT INT DEFAULT 0 COMMENT '조회수',
    PIN_YN CHAR(1) DEFAULT 'N' COMMENT '상단고정',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    REG_USER VARCHAR(20) COMMENT '등록자',
    UPD_DT DATETIME COMMENT '수정일시',
    UPD_USER VARCHAR(20) COMMENT '수정자',
    PRIMARY KEY (NOTICE_ID),
    INDEX IDX_TW_NOTICE_01 (COMP_CD, BOARD_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공지사항/게시판';

-- 54. TW_LOGIN_HIST - 로그인 이력
DROP TABLE IF EXISTS TW_LOGIN_HIST;
CREATE TABLE IF NOT EXISTS TW_LOGIN_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '이력ID',
    COMP_CD VARCHAR(10) COMMENT '회사구분',
    USER_ID VARCHAR(50) COMMENT '사용자ID',
    LOGIN_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '로그인일시',
    LOGOUT_DT DATETIME COMMENT '로그아웃일시',
    IP_ADDR VARCHAR(50) COMMENT 'IP주소',
    USER_AGENT VARCHAR(500) COMMENT '브라우저정보',
    RESULT VARCHAR(20) COMMENT '결과(성공/실패)',
    NOTE VARCHAR(255) COMMENT '비고',
    PRIMARY KEY (HIST_ID),
    INDEX IDX_TW_LOGIN_HIST_01 (USER_ID, LOGIN_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='로그인 이력';

-- 55. TW_SMS - SMS 발송이력
DROP TABLE IF EXISTS TW_SMS;
CREATE TABLE IF NOT EXISTS TW_SMS (
    SMS_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'SMS_ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    SEND_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '발송일시',
    SENDER VARCHAR(50) COMMENT '발신자',
    RECEIVER VARCHAR(50) COMMENT '수신자',
    PHONE_NO VARCHAR(20) COMMENT '수신번호',
    MSG_CONTENT VARCHAR(1000) COMMENT '메시지내용',
    SEND_RESULT VARCHAR(20) COMMENT '발송결과(성공/실패)',
    NOTE VARCHAR(255) COMMENT '비고',
    PRIMARY KEY (SMS_ID),
    INDEX IDX_TW_SMS_01 (COMP_CD, SEND_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SMS 발송이력';

-- 56. TW_CERTIFY_SCHEDULE - 인증 일정관리
DROP TABLE IF EXISTS TW_CERTIFY_SCHEDULE;
CREATE TABLE IF NOT EXISTS TW_CERTIFY_SCHEDULE (
    CERT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '인증일정ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    CERT_CYCLE VARCHAR(20) COMMENT '인증주기(3주기/4주기)',
    CERT_TYPE VARCHAR(20) COMMENT '인증유형(본인증/중간자체/갱신)',
    PLAN_DT VARCHAR(10) COMMENT '예정일',
    ACTUAL_DT VARCHAR(10) COMMENT '실시일',
    CERT_STATUS VARCHAR(20) DEFAULT '예정' COMMENT '상태(예정/진행/완료)',
    CERT_RESULT VARCHAR(20) COMMENT '결과(인증/조건부/불인증)',
    SURVEYOR VARCHAR(200) COMMENT '조사위원',
    SURVEY_DAYS INT COMMENT '조사일수',
    PREP_STATUS VARCHAR(20) COMMENT '준비상태',
    NOTE TEXT COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (CERT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='인증 일정관리';

-- 57. TW_FORM_COMPLETE - 완결도 점검 (요양 3주기)
DROP TABLE IF EXISTS TW_FORM_COMPLETE;
CREATE TABLE IF NOT EXISTS TW_FORM_COMPLETE (
    FC_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '점검ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DISCHARGE_DT VARCHAR(10) NOT NULL COMMENT '퇴원일자',
    PAT_CD VARCHAR(20) NOT NULL COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    EVAL_ROUND VARCHAR(20) NOT NULL COMMENT '차수(1차/2차)',
    FORM_TYPE VARCHAR(20) DEFAULT 'NURSING' COMMENT '유형(NURSING/DOCTOR/REHAB/PSY)',
    SEC1_ITEMS TEXT COMMENT '섹션1 항목결과(JSON)',
    SEC2_ITEMS TEXT COMMENT '섹션2 항목결과(JSON)',
    SEC3_ITEMS TEXT COMMENT '섹션3 항목결과(JSON)',
    SEC4_ITEMS TEXT COMMENT '섹션4 항목결과(JSON)',
    SEC5_ITEMS TEXT COMMENT '섹션5 항목결과(JSON)',
    SEC6_ITEMS TEXT COMMENT '섹션6 항목결과(JSON)',
    TOTAL_ITEMS INT DEFAULT 0 COMMENT '전체항목수',
    PASS_ITEMS INT DEFAULT 0 COMMENT '충족항목수',
    COMPLETE_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '완결률(%)',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (FC_ID),
    INDEX IDX_TW_FC_01 (COMP_CD, DISCHARGE_DT, PAT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='완결도 점검';

-- 58. TW_DEPT - 부서 마스터
DROP TABLE IF EXISTS TW_DEPT;
CREATE TABLE IF NOT EXISTS TW_DEPT (
    DEPT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '부서ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DEPT_CD VARCHAR(20) NOT NULL COMMENT '부서코드',
    DEPT_NM VARCHAR(100) COMMENT '부서명',
    PARENT_CD VARCHAR(20) COMMENT '상위부서코드',
    DEPT_TYPE VARCHAR(50) COMMENT '부서유형(진료/간호/행정/지원)',
    SORT_ORD INT DEFAULT 0 COMMENT '정렬순서',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (DEPT_ID),
    UNIQUE INDEX IDX_TW_DEPT_01 (COMP_CD, DEPT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='부서 마스터';

-- 59. TW_DEPT_MEMBER - 부서 소속직원
DROP TABLE IF EXISTS TW_DEPT_MEMBER;
CREATE TABLE IF NOT EXISTS TW_DEPT_MEMBER (
    DM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '소속ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DEPT_CD VARCHAR(20) NOT NULL COMMENT '부서코드',
    STAFF_ID BIGINT NOT NULL COMMENT '직원ID',
    ROLE_IN_DEPT VARCHAR(50) COMMENT '부서내역할(부서장/팀장/팀원)',
    START_DT VARCHAR(10) COMMENT '배치일',
    END_DT VARCHAR(10) COMMENT '종료일',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DM_ID),
    INDEX IDX_TW_DM_01 (COMP_CD, DEPT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='부서 소속직원';

-- 60. TW_WARD - 병동 마스터
DROP TABLE IF EXISTS TW_WARD;
CREATE TABLE IF NOT EXISTS TW_WARD (
    WARD_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '병동ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    WARD_CD VARCHAR(20) NOT NULL COMMENT '병동코드',
    WARD_NM VARCHAR(100) COMMENT '병동명',
    WARD_TYPE VARCHAR(50) COMMENT '병동유형(일반/중환자/치매전담 등)',
    FLOOR VARCHAR(20) COMMENT '층',
    BED_CNT INT DEFAULT 0 COMMENT '병상수',
    NURSE_STATION VARCHAR(50) COMMENT '간호스테이션',
    SORT_ORD INT DEFAULT 0 COMMENT '정렬순서',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (WARD_ID),
    UNIQUE INDEX IDX_TW_WARD_01 (COMP_CD, WARD_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='병동 마스터';

-- 61. TW_WARD_MEMBER - 병동 소속직원
DROP TABLE IF EXISTS TW_WARD_MEMBER;
CREATE TABLE IF NOT EXISTS TW_WARD_MEMBER (
    WM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '소속ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    WARD_CD VARCHAR(20) NOT NULL COMMENT '병동코드',
    STAFF_ID BIGINT NOT NULL COMMENT '직원ID',
    ROLE_IN_WARD VARCHAR(50) COMMENT '병동내역할(수간호사/간호사/간병인)',
    START_DT VARCHAR(10) COMMENT '배치일',
    END_DT VARCHAR(10) COMMENT '종료일',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (WM_ID),
    INDEX IDX_TW_WM_01 (COMP_CD, WARD_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='병동 소속직원';

-- 62. TW_TEAM - 팀/위원회 마스터
DROP TABLE IF EXISTS TW_TEAM;
CREATE TABLE IF NOT EXISTS TW_TEAM (
    TEAM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '팀ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    TEAM_CD VARCHAR(20) COMMENT '팀코드',
    TEAM_NM VARCHAR(100) COMMENT '팀명',
    TEAM_TYPE VARCHAR(50) COMMENT '유형(인증TFT/QI팀/감염관리팀/약사위원회 등)',
    LEADER VARCHAR(50) COMMENT '팀장',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (TEAM_ID),
    INDEX IDX_TW_TEAM_01 (COMP_CD, TEAM_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='팀/위원회 마스터';

-- 63. TW_TEAM_MEMBER - 팀/위원회 구성원
DROP TABLE IF EXISTS TW_TEAM_MEMBER;
CREATE TABLE IF NOT EXISTS TW_TEAM_MEMBER (
    TM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '구성원ID',
    TEAM_ID BIGINT NOT NULL COMMENT '팀ID',
    STAFF_ID BIGINT COMMENT '직원ID',
    MEMBER_NM VARCHAR(50) COMMENT '구성원명',
    ROLE_IN_TEAM VARCHAR(50) COMMENT '팀내역할(위원장/위원/간사)',
    DEPT_NM VARCHAR(50) COMMENT '소속부서',
    JOB_TYPE VARCHAR(50) COMMENT '직종',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TM_ID),
    INDEX IDX_TW_TM_01 (TEAM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='팀/위원회 구성원';

-- 64. TW_COMMITTEE_MEMBER - 위원회 위원 명부
DROP TABLE IF EXISTS TW_COMMITTEE_MEMBER;
CREATE TABLE IF NOT EXISTS TW_COMMITTEE_MEMBER (
    CM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '위원ID',
    COMM_ID BIGINT COMMENT '위원회활동ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    COMM_TYPE VARCHAR(50) COMMENT '위원회유형',
    MEMBER_NM VARCHAR(50) COMMENT '위원명',
    DEPT_NM VARCHAR(50) COMMENT '소속',
    POSITION VARCHAR(50) COMMENT '직위',
    ROLE_IN_COMM VARCHAR(50) COMMENT '위원회역할(위원장/부위원장/위원/간사)',
    ATTEND_YN CHAR(1) COMMENT '참석여부',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CM_ID),
    INDEX IDX_TW_CM_01 (COMP_CD, COMM_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='위원회 위원 명부';

-- 65. TW_POSITION - 직위/직급 코드
DROP TABLE IF EXISTS TW_POSITION;
CREATE TABLE IF NOT EXISTS TW_POSITION (
    POS_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '직위ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    POS_CD VARCHAR(20) NOT NULL COMMENT '직위코드',
    POS_NM VARCHAR(50) COMMENT '직위명',
    POS_TYPE VARCHAR(50) COMMENT '유형(직위/직급/직종)',
    SORT_ORD INT DEFAULT 0 COMMENT '정렬순서',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (POS_ID),
    INDEX IDX_TW_POS_01 (COMP_CD, POS_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='직위/직급 코드';

-- 66. TW_PATHOLOGY_TAT - 검체 TAT
DROP TABLE IF EXISTS TW_PATHOLOGY_TAT;
CREATE TABLE IF NOT EXISTS TW_PATHOLOGY_TAT (
    PTAT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '검체TAT_ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    TEST_DT VARCHAR(10) NOT NULL COMMENT '검사일',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    TEST_TYPE VARCHAR(50) COMMENT '검사유형(혈액/소변/미생물/조직)',
    TEST_NM VARCHAR(100) COMMENT '검사명',
    ORDER_DT DATETIME COMMENT '처방일시',
    COLLECT_DT DATETIME COMMENT '채취일시',
    RECV_DT DATETIME COMMENT '접수일시',
    REPORT_DT DATETIME COMMENT '보고일시',
    TAT_MIN INT COMMENT 'TAT(분)',
    GOAL_MIN INT COMMENT '목표TAT(분)',
    ACHIEVE_YN CHAR(1) COMMENT '달성여부',
    VENDOR VARCHAR(50) COMMENT '수탁기관',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (PTAT_ID),
    INDEX IDX_TW_PTAT_01 (COMP_CD, TEST_DT, TEST_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='검체 TAT';

-- 67. TW_RESTRAINT_RECORD - 격리/강박 상세기록
DROP TABLE IF EXISTS TW_RESTRAINT_RECORD;
CREATE TABLE IF NOT EXISTS TW_RESTRAINT_RECORD (
    REC_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '기록ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) NOT NULL COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    REC_DT VARCHAR(10) NOT NULL COMMENT '기록일',
    REC_TYPE VARCHAR(20) COMMENT '유형(격리/강박/보호대)',
    START_DT DATETIME COMMENT '시작일시',
    END_DT DATETIME COMMENT '해제일시',
    DURATION_MIN INT COMMENT '적용시간(분)',
    REASON TEXT COMMENT '적용사유',
    BODY_PART VARCHAR(100) COMMENT '적용부위',
    ORDER_DR VARCHAR(50) COMMENT '처방의',
    ORDER_DT DATETIME COMMENT '처방일시',
    RENEW_DT DATETIME COMMENT '재처방일시',
    FAMILY_NOTIFY_YN CHAR(1) COMMENT '보호자통지여부',
    FAMILY_NOTIFY_DT DATETIME COMMENT '통지일시',
    OBSERVE_INTERVAL VARCHAR(20) COMMENT '관찰간격',
    RELEASE_REASON VARCHAR(200) COMMENT '해제사유',
    NOTE TEXT COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (REC_ID),
    INDEX IDX_TW_RR_01 (COMP_CD, PAT_CD, REC_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='격리/강박 상세기록';

-- 68. TW_GUIDEBOOK - 규정/지침 관리
DROP TABLE IF EXISTS TW_GUIDEBOOK;
CREATE TABLE IF NOT EXISTS TW_GUIDEBOOK (
    GUIDE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '규정ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    GUIDE_TYPE VARCHAR(50) COMMENT '유형(규정/지침/매뉴얼/프로토콜)',
    GUIDE_CD VARCHAR(50) COMMENT '규정번호',
    GUIDE_NM VARCHAR(200) COMMENT '규정명',
    DEPT_NM VARCHAR(50) COMMENT '관리부서',
    VER VARCHAR(10) DEFAULT '1.0' COMMENT '버전',
    APPROVE_DT VARCHAR(10) COMMENT '승인일',
    EFFECTIVE_DT VARCHAR(10) COMMENT '시행일',
    REVIEW_DT VARCHAR(10) COMMENT '검토예정일',
    REVIEW_CYCLE VARCHAR(20) COMMENT '검토주기(1년/2년/3년)',
    CONTENT LONGTEXT COMMENT '규정내용',
    RELATED_CERT VARCHAR(100) COMMENT '관련 인증기준',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (GUIDE_ID),
    INDEX IDX_TW_GUIDE_01 (COMP_CD, GUIDE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='규정/지침 관리';

-- 69. TW_VACATION - 직원 휴가관리
DROP TABLE IF EXISTS TW_VACATION;
CREATE TABLE IF NOT EXISTS TW_VACATION (
    VAC_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '휴가ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    STAFF_ID BIGINT COMMENT '직원ID',
    EMP_NM VARCHAR(50) COMMENT '직원명',
    DEPT_NM VARCHAR(50) COMMENT '부서',
    VAC_TYPE VARCHAR(50) COMMENT '휴가유형(연차/병가/공가/특별)',
    START_DT VARCHAR(10) COMMENT '시작일',
    END_DT VARCHAR(10) COMMENT '종료일',
    VAC_DAYS DECIMAL(5,1) DEFAULT 0 COMMENT '휴가일수',
    REASON VARCHAR(500) COMMENT '사유',
    APPROVE_STATUS VARCHAR(20) DEFAULT '신청' COMMENT '상태(신청/승인/반려)',
    APPROVER VARCHAR(50) COMMENT '승인자',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (VAC_ID),
    INDEX IDX_TW_VAC_01 (COMP_CD, EMP_NM, START_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='직원 휴가관리';

-- 70. TW_WARD_DEVICE - 병동 장비관리
DROP TABLE IF EXISTS TW_WARD_DEVICE;
CREATE TABLE IF NOT EXISTS TW_WARD_DEVICE (
    WD_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '장비ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    WARD_CD VARCHAR(20) COMMENT '병동코드',
    DEVICE_NM VARCHAR(100) COMMENT '장비명',
    MODEL_NM VARCHAR(50) COMMENT '모델명',
    SERIAL_NO VARCHAR(50) COMMENT '일련번호',
    PURCHASE_DT VARCHAR(10) COMMENT '구입일',
    INSPECT_CYCLE VARCHAR(20) COMMENT '점검주기',
    LAST_INSPECT_DT VARCHAR(10) COMMENT '최근점검일',
    DEVICE_STATUS VARCHAR(20) DEFAULT '정상' COMMENT '상태(정상/고장/수리중/폐기)',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (WD_ID),
    INDEX IDX_TW_WD_01 (COMP_CD, WARD_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='병동 장비관리';

-- 71. TW_WARD_DEVICE_HIST - 병동 장비 점검이력
DROP TABLE IF EXISTS TW_WARD_DEVICE_HIST;
CREATE TABLE IF NOT EXISTS TW_WARD_DEVICE_HIST (
    WDH_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '이력ID',
    WD_ID BIGINT NOT NULL COMMENT '장비ID',
    CHK_DT VARCHAR(10) COMMENT '점검일',
    CHK_TYPE VARCHAR(50) COMMENT '점검유형(정기/수시/수리)',
    CHK_RESULT VARCHAR(50) COMMENT '점검결과(양호/불량/수리필요)',
    CHK_CONTENT TEXT COMMENT '점검내용',
    CHECKER VARCHAR(50) COMMENT '점검자',
    NOTE VARCHAR(255) COMMENT '비고',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (WDH_ID),
    INDEX IDX_TW_WDH_01 (WD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='병동 장비 점검이력';

-- 72. TW_COMPANY_INFO - 병원 인증현황 (from T_COMPANY_INFO)
DROP TABLE IF EXISTS TW_COMPANY_INFO;
CREATE TABLE IF NOT EXISTS TW_COMPANY_INFO (
    INFO_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '정보ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    INFO_TYPE VARCHAR(50) COMMENT '유형(방문기록/연락처/특이사항)',
    INFO_DT VARCHAR(10) COMMENT '일자',
    TITLE VARCHAR(200) COMMENT '제목',
    CONTENT TEXT COMMENT '내용',
    CONTACT_NM VARCHAR(50) COMMENT '담당자',
    CONTACT_TEL VARCHAR(20) COMMENT '연락처',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (INFO_ID),
    INDEX IDX_TW_CI_01 (COMP_CD, INFO_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='병원 인증현황';

-- 73. TW_COMPANY_CONFIRM - 병원 업무확인
DROP TABLE IF EXISTS TW_COMPANY_CONFIRM;
CREATE TABLE IF NOT EXISTS TW_COMPANY_CONFIRM (
    CONFIRM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '확인ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    CONFIRM_DT VARCHAR(10) NOT NULL COMMENT '확인일',
    CONFIRM_TYPE VARCHAR(50) COMMENT '확인유형',
    TITLE VARCHAR(200) COMMENT '제목',
    CONTENT TEXT COMMENT '내용',
    CONFIRMER VARCHAR(50) COMMENT '확인자',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (CONFIRM_ID),
    INDEX IDX_TW_CC_01 (COMP_CD, CONFIRM_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='병원 업무확인';

-- 74. TW_BOARD - 게시판
DROP TABLE IF EXISTS TW_BOARD;
CREATE TABLE IF NOT EXISTS TW_BOARD (
    BOARD_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '게시글ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    BOARD_TYPE VARCHAR(20) DEFAULT 'GENERAL' COMMENT '게시판유형(GENERAL/CERT/QPS/INFECTION)',
    TITLE VARCHAR(200) NOT NULL COMMENT '제목',
    CONTENT LONGTEXT COMMENT '내용',
    WRITER VARCHAR(50) COMMENT '작성자',
    DEPT_NM VARCHAR(50) COMMENT '부서',
    VIEW_CNT INT DEFAULT 0 COMMENT '조회수',
    PIN_YN CHAR(1) DEFAULT 'N' COMMENT '상단고정',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (BOARD_ID),
    INDEX IDX_TW_BOARD_01 (COMP_CD, BOARD_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판';

-- 75. TW_PHARM_PATIENT - 환자별 투약관리
DROP TABLE IF EXISTS TW_PHARM_PATIENT;
CREATE TABLE IF NOT EXISTS TW_PHARM_PATIENT (
    PP_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '투약ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) NOT NULL COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    WARD_NM VARCHAR(50) COMMENT '병동',
    DRUG_NM VARCHAR(200) COMMENT '약품명',
    DRUG_CD VARCHAR(50) COMMENT '약품코드',
    DOSAGE VARCHAR(50) COMMENT '용량',
    ROUTE VARCHAR(50) COMMENT '투여경로(경구/주사/외용)',
    FREQUENCY VARCHAR(50) COMMENT '투여횟수',
    START_DT VARCHAR(10) COMMENT '시작일',
    END_DT VARCHAR(10) COMMENT '종료일',
    ORDER_DR VARCHAR(50) COMMENT '처방의',
    ALLERGY_CHK_YN CHAR(1) COMMENT '알러지확인',
    HIGH_RISK_YN CHAR(1) COMMENT '고위험약물여부',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (PP_ID),
    INDEX IDX_TW_PP_01 (COMP_CD, PAT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='환자별 투약관리';

-- ============================================================
-- 추가 테이블 (정신과/재활 확장 + 실업무)
-- ============================================================

-- 76. TW_FORM_COMPLETE_PSY - 완결도 점검 (정신과)
DROP TABLE IF EXISTS TW_FORM_COMPLETE_PSY;
CREATE TABLE IF NOT EXISTS TW_FORM_COMPLETE_PSY (
    FCP_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '점검ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DISCHARGE_DT VARCHAR(10) NOT NULL COMMENT '퇴원일자',
    PAT_CD VARCHAR(20) NOT NULL COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    EVAL_ROUND VARCHAR(20) NOT NULL COMMENT '차수(1차/2차)',
    SEC1_ITEMS TEXT COMMENT '정신과초기평가(JSON)',
    SEC2_ITEMS TEXT COMMENT '경과기록(JSON)',
    SEC3_ITEMS TEXT COMMENT '간호초기평가(JSON)',
    SEC4_ITEMS TEXT COMMENT '간호기록(JSON)',
    SEC5_ITEMS TEXT COMMENT '진단코드(JSON)',
    TOTAL_ITEMS INT DEFAULT 0 COMMENT '전체항목수',
    PASS_ITEMS INT DEFAULT 0 COMMENT '충족항목수',
    COMPLETE_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '완결률(%)',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (FCP_ID),
    INDEX IDX_TW_FCP_01 (COMP_CD, DISCHARGE_DT, PAT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='완결도 점검(정신과)';

-- 77. TW_FORM_COMPLETE_REHAB - 완결도 점검 (재활)
DROP TABLE IF EXISTS TW_FORM_COMPLETE_REHAB;
CREATE TABLE IF NOT EXISTS TW_FORM_COMPLETE_REHAB (
    FCR_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '점검ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    DISCHARGE_DT VARCHAR(10) NOT NULL COMMENT '퇴원일자',
    PAT_CD VARCHAR(20) NOT NULL COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    EVAL_ROUND VARCHAR(20) NOT NULL COMMENT '차수(1차/2차)',
    SEC1_ITEMS TEXT COMMENT '전과기록(JSON)',
    SEC2_ITEMS TEXT COMMENT '퇴원요약(JSON)',
    SEC3_ITEMS TEXT COMMENT '의학적초기평가(JSON)',
    SEC4_ITEMS TEXT COMMENT '간호초기평가(JSON)',
    SEC5_ITEMS TEXT COMMENT '의사경과기록(JSON)',
    SEC6_ITEMS TEXT COMMENT '간호기록(JSON)',
    SEC7_ITEMS TEXT COMMENT '치료사경과기록(JSON)',
    SEC8_ITEMS TEXT COMMENT '동의서(JSON)',
    SEC9_ITEMS TEXT COMMENT '진단코드/처치코드(JSON)',
    TOTAL_ITEMS INT DEFAULT 0 COMMENT '전체항목수',
    PASS_ITEMS INT DEFAULT 0 COMMENT '충족항목수',
    COMPLETE_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '완결률(%)',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (FCR_ID),
    INDEX IDX_TW_FCR_01 (COMP_CD, DISCHARGE_DT, PAT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='완결도 점검(재활)';

-- 78. TW_PATIENT_CHART - 환자 차트 마스터
DROP TABLE IF EXISTS TW_PATIENT_CHART;
CREATE TABLE IF NOT EXISTS TW_PATIENT_CHART (
    CHART_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '차트ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PAT_CD VARCHAR(20) NOT NULL COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    CHART_TYPE VARCHAR(50) COMMENT '차트유형(초기평가/경과기록/간호기록/투약기록 등)',
    CHART_DT VARCHAR(10) COMMENT '기록일',
    CHART_CONTENT LONGTEXT COMMENT '기록내용',
    WRITER VARCHAR(50) COMMENT '작성자',
    WRITER_DEPT VARCHAR(50) COMMENT '작성자부서',
    WRITER_JOB VARCHAR(50) COMMENT '작성자직종',
    SIGN_STATUS VARCHAR(20) DEFAULT '작성' COMMENT '서명상태(작성/서명완료)',
    SIGN_DT DATETIME COMMENT '서명일시',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (CHART_ID),
    INDEX IDX_TW_PC_01 (COMP_CD, PAT_CD, CHART_TYPE),
    INDEX IDX_TW_PC_02 (COMP_CD, CHART_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='환자 차트 마스터';

-- 79. TW_PATIENT_CHART_DTL - 환자 차트 상세
DROP TABLE IF EXISTS TW_PATIENT_CHART_DTL;
CREATE TABLE IF NOT EXISTS TW_PATIENT_CHART_DTL (
    DTL_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '상세ID',
    CHART_ID BIGINT NOT NULL COMMENT '차트ID',
    ITEM_KEY VARCHAR(50) COMMENT '항목키',
    ITEM_NM VARCHAR(200) COMMENT '항목명',
    ITEM_VAL TEXT COMMENT '항목값',
    SORT_ORD INT DEFAULT 0 COMMENT '정렬순서',
    NOTE VARCHAR(255) COMMENT '비고',
    PRIMARY KEY (DTL_ID),
    INDEX IDX_TW_PCD_01 (CHART_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='환자 차트 상세';

-- 80. TW_CHART_SIGN - 차트 전자서명
DROP TABLE IF EXISTS TW_CHART_SIGN;
CREATE TABLE IF NOT EXISTS TW_CHART_SIGN (
    CS_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '서명ID',
    CHART_ID BIGINT NOT NULL COMMENT '차트ID',
    SIGNER VARCHAR(50) COMMENT '서명자',
    SIGN_TYPE VARCHAR(20) COMMENT '서명유형(작성자/확인자/공동서명)',
    SIGN_DT DATETIME COMMENT '서명일시',
    SIGN_IMG MEDIUMBLOB COMMENT '서명이미지',
    NOTE VARCHAR(255) COMMENT '비고',
    PRIMARY KEY (CS_ID),
    INDEX IDX_TW_CS_01 (CHART_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='차트 전자서명';

-- 81. TW_CHART_LOG - 차트 접근이력
DROP TABLE IF EXISTS TW_CHART_LOG;
CREATE TABLE IF NOT EXISTS TW_CHART_LOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '로그ID',
    COMP_CD VARCHAR(10) COMMENT '회사구분',
    CHART_ID BIGINT COMMENT '차트ID',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    ACTION_TYPE VARCHAR(20) COMMENT '행위(조회/수정/출력/삭제)',
    ACTION_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '행위일시',
    USER_ID VARCHAR(50) COMMENT '사용자ID',
    USER_NM VARCHAR(50) COMMENT '사용자명',
    IP_ADDR VARCHAR(50) COMMENT 'IP주소',
    NOTE VARCHAR(255) COMMENT '비고',
    PRIMARY KEY (LOG_ID),
    INDEX IDX_TW_CL_01 (COMP_CD, CHART_ID),
    INDEX IDX_TW_CL_02 (PAT_CD, ACTION_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='차트 접근이력';

-- 82. TW_STAFF_REPORT - 직원 일일보고
DROP TABLE IF EXISTS TW_STAFF_REPORT;
CREATE TABLE IF NOT EXISTS TW_STAFF_REPORT (
    RPT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '보고ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    RPT_DT VARCHAR(10) NOT NULL COMMENT '보고일',
    EMP_NM VARCHAR(50) COMMENT '직원명',
    DEPT_NM VARCHAR(50) COMMENT '부서',
    RPT_TYPE VARCHAR(50) COMMENT '보고유형(일일업무/인수인계/특이사항)',
    RPT_CONTENT TEXT COMMENT '보고내용',
    ACTION_NEEDED TEXT COMMENT '조치필요사항',
    CONFIRM_YN CHAR(1) DEFAULT 'N' COMMENT '확인여부',
    CONFIRMER VARCHAR(50) COMMENT '확인자',
    CONFIRM_DT DATETIME COMMENT '확인일시',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (RPT_ID),
    INDEX IDX_TW_SR_01 (COMP_CD, RPT_DT, DEPT_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='직원 일일보고';

-- 83. TW_DUTY_CONFIRM - 근무표 승인
DROP TABLE IF EXISTS TW_DUTY_CONFIRM;
CREATE TABLE IF NOT EXISTS TW_DUTY_CONFIRM (
    DC_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '승인ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    SCHED_MONTH VARCHAR(7) NOT NULL COMMENT '근무월(YYYY-MM)',
    DEPT_CD VARCHAR(20) COMMENT '부서코드',
    DEPT_NM VARCHAR(50) COMMENT '부서명',
    SUBMIT_DT DATETIME COMMENT '제출일시',
    SUBMIT_USER VARCHAR(50) COMMENT '제출자',
    APPROVE_STATUS VARCHAR(20) DEFAULT '제출' COMMENT '상태(제출/승인/반려)',
    APPROVER VARCHAR(50) COMMENT '승인자',
    APPROVE_DT DATETIME COMMENT '승인일시',
    REJECT_REASON VARCHAR(500) COMMENT '반려사유',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DC_ID),
    INDEX IDX_TW_DC_01 (COMP_CD, SCHED_MONTH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='근무표 승인';

-- 84. TW_WORK_PLAN - 업무 일정계획
DROP TABLE IF EXISTS TW_WORK_PLAN;
CREATE TABLE IF NOT EXISTS TW_WORK_PLAN (
    PLAN_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '계획ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    PLAN_TYPE VARCHAR(50) COMMENT '유형(인증준비/교육/점검/회의/기타)',
    PLAN_TITLE VARCHAR(200) COMMENT '제목',
    PLAN_CONTENT TEXT COMMENT '내용',
    START_DT VARCHAR(10) COMMENT '시작일',
    END_DT VARCHAR(10) COMMENT '종료일',
    RESPONSIBLE VARCHAR(50) COMMENT '담당자',
    DEPT_NM VARCHAR(50) COMMENT '담당부서',
    PLAN_STATUS VARCHAR(20) DEFAULT '예정' COMMENT '상태(예정/진행/완료/취소)',
    PRIORITY VARCHAR(10) COMMENT '우선순위(상/중/하)',
    PROGRESS INT DEFAULT 0 COMMENT '진행률(%)',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (PLAN_ID),
    INDEX IDX_TW_WP_01 (COMP_CD, PLAN_TYPE, START_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='업무 일정계획';

-- ============================================================
-- 추가 테이블 (인증 실사 핵심 업무)
-- ============================================================

-- 85. TW_MOCK_SURVEY - 모의조사 관리
DROP TABLE IF EXISTS TW_MOCK_SURVEY;
CREATE TABLE IF NOT EXISTS TW_MOCK_SURVEY (
    SURVEY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '모의조사ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    SURVEY_DT VARCHAR(10) COMMENT '조사일자',
    SURVEY_TYPE VARCHAR(50) COMMENT '유형(전체모의/부분모의/서류점검)',
    SURVEY_TITLE VARCHAR(200) COMMENT '조사명',
    SURVEYOR VARCHAR(200) COMMENT '조사위원(외부/내부)',
    TARGET_AREA VARCHAR(200) COMMENT '대상영역',
    TOTAL_ITEMS INT DEFAULT 0 COMMENT '총 점검항목수',
    PASS_ITEMS INT DEFAULT 0 COMMENT '충족항목수',
    FAIL_ITEMS INT DEFAULT 0 COMMENT '미충족항목수',
    SCORE DECIMAL(5,2) DEFAULT 0 COMMENT '점수',
    STRENGTH TEXT COMMENT '우수사항',
    WEAKNESS TEXT COMMENT '미흡사항',
    IMPROVE_PLAN TEXT COMMENT '개선계획',
    NOTE TEXT COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (SURVEY_ID),
    INDEX IDX_TW_MS_01 (COMP_CD, SURVEY_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='모의조사 관리';

-- 86. TW_SELF_CHECK - 부서별 자체점검
DROP TABLE IF EXISTS TW_SELF_CHECK;
CREATE TABLE IF NOT EXISTS TW_SELF_CHECK (
    CHECK_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '점검ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    CHECK_DT VARCHAR(10) NOT NULL COMMENT '점검일',
    CHECK_MONTH VARCHAR(7) COMMENT '점검월(YYYY-MM)',
    DEPT_NM VARCHAR(50) COMMENT '점검부서',
    CHECK_TYPE VARCHAR(50) COMMENT '점검유형(환자안전/감염관리/시설환경/서류)',
    NODE_ID VARCHAR(20) COMMENT '인증기준 노드ID',
    NODE_NM VARCHAR(200) COMMENT '인증기준명',
    TOTAL_ITEMS INT DEFAULT 0 COMMENT '총 점검항목',
    PASS_ITEMS INT DEFAULT 0 COMMENT '적합',
    FAIL_ITEMS INT DEFAULT 0 COMMENT '부적합',
    NA_ITEMS INT DEFAULT 0 COMMENT '해당없음',
    COMPLY_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '적합률(%)',
    FAIL_DESC TEXT COMMENT '부적합 내용',
    IMPROVE_DESC TEXT COMMENT '개선사항',
    CHECKER VARCHAR(50) COMMENT '점검자',
    CONFIRM_YN CHAR(1) DEFAULT 'N' COMMENT '확인여부',
    CONFIRMER VARCHAR(50) COMMENT '확인자',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (CHECK_ID),
    INDEX IDX_TW_SC_01 (COMP_CD, CHECK_MONTH, DEPT_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='부서별 자체점검';

-- 87. TW_CERT_DOC_STATUS - 인증자료 준비현황
DROP TABLE IF EXISTS TW_CERT_DOC_STATUS;
CREATE TABLE IF NOT EXISTS TW_CERT_DOC_STATUS (
    DOC_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '자료ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    NODE_ID VARCHAR(20) COMMENT '인증기준 노드ID',
    NODE_NM VARCHAR(200) COMMENT '인증기준명',
    CHAPTER_NM VARCHAR(100) COMMENT '장명',
    DOC_TYPE VARCHAR(50) COMMENT '자료유형(규정/지침/서식/기록/교육자료/통계)',
    DOC_NM VARCHAR(200) COMMENT '자료명',
    DEPT_NM VARCHAR(50) COMMENT '담당부서',
    MANAGER VARCHAR(50) COMMENT '담당자',
    DOC_STATUS VARCHAR(20) DEFAULT '미작성' COMMENT '상태(미작성/작성중/검토중/완료)',
    DUE_DT VARCHAR(10) COMMENT '목표완료일',
    COMPLETE_DT VARCHAR(10) COMMENT '완료일',
    FILE_YN CHAR(1) DEFAULT 'N' COMMENT '파일첨부여부',
    REVIEW_COMMENT TEXT COMMENT '검토의견',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    UPD_DT DATETIME,
    UPD_USER VARCHAR(20),
    PRIMARY KEY (DOC_ID),
    INDEX IDX_TW_CDS_01 (COMP_CD, NODE_ID, DOC_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='인증자료 준비현황';

-- 88. TW_TEMP_LOG - 냉장고/온도 기록
DROP TABLE IF EXISTS TW_TEMP_LOG;
CREATE TABLE IF NOT EXISTS TW_TEMP_LOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '기록ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    LOG_DT VARCHAR(10) NOT NULL COMMENT '기록일',
    LOG_TIME VARCHAR(5) COMMENT '기록시간(HH:MM)',
    EQUIP_TYPE VARCHAR(50) COMMENT '장비유형(약품냉장고/혈액냉장고/검체냉장고/백신냉장고)',
    EQUIP_LOCATION VARCHAR(100) COMMENT '설치위치',
    TEMP_VALUE DECIMAL(5,1) COMMENT '온도(℃)',
    TEMP_MIN DECIMAL(5,1) COMMENT '기준최저온도',
    TEMP_MAX DECIMAL(5,1) COMMENT '기준최고온도',
    NORMAL_YN CHAR(1) COMMENT '정상여부(Y/N)',
    ACTION_DESC VARCHAR(500) COMMENT '이상 시 조치사항',
    RECORDER VARCHAR(50) COMMENT '기록자',
    NOTE VARCHAR(255) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (LOG_ID),
    INDEX IDX_TW_TL_01 (COMP_CD, LOG_DT, EQUIP_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='냉장고/온도 기록';

-- 89. TW_SATISFACTION - 환자/직원 만족도
DROP TABLE IF EXISTS TW_SATISFACTION;
CREATE TABLE IF NOT EXISTS TW_SATISFACTION (
    SAT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '만족도ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    SURVEY_YEAR VARCHAR(4) COMMENT '조사년도',
    SURVEY_HALF VARCHAR(10) COMMENT '조사반기(상반기/하반기)',
    SAT_TYPE VARCHAR(20) COMMENT '유형(환자/보호자/직원)',
    TOTAL_CNT INT DEFAULT 0 COMMENT '조사대상',
    RESPONSE_CNT INT DEFAULT 0 COMMENT '응답수',
    RESPONSE_RATE DECIMAL(5,2) DEFAULT 0 COMMENT '응답률(%)',
    AVG_SCORE DECIMAL(5,2) DEFAULT 0 COMMENT '평균점수(5점만점)',
    Q1_SCORE DECIMAL(5,2) COMMENT '항목1점수(진료만족)',
    Q2_SCORE DECIMAL(5,2) COMMENT '항목2점수(간호만족)',
    Q3_SCORE DECIMAL(5,2) COMMENT '항목3점수(시설만족)',
    Q4_SCORE DECIMAL(5,2) COMMENT '항목4점수(식사만족)',
    Q5_SCORE DECIMAL(5,2) COMMENT '항목5점수(전반만족)',
    IMPROVE_DESC TEXT COMMENT '개선사항',
    NOTE VARCHAR(500) COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (SAT_ID),
    INDEX IDX_TW_SAT_01 (COMP_CD, SURVEY_YEAR, SAT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='환자/직원 만족도';

-- 90. TW_EMERGENCY - 응급상황 기록
DROP TABLE IF EXISTS TW_EMERGENCY;
CREATE TABLE IF NOT EXISTS TW_EMERGENCY (
    EMG_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '응급ID',
    COMP_CD VARCHAR(10) NOT NULL COMMENT '회사구분',
    EMG_DT DATETIME COMMENT '발생일시',
    PAT_CD VARCHAR(20) COMMENT '환자번호',
    PAT_NM VARCHAR(50) COMMENT '환자명',
    WARD_NM VARCHAR(50) COMMENT '발생병동',
    EMG_TYPE VARCHAR(50) COMMENT '유형(심정지/호흡곤란/의식변화/대량출혈/경련/기타)',
    EMG_DESC TEXT COMMENT '상황설명',
    FIRST_RESPONDER VARCHAR(50) COMMENT '최초발견자',
    FIRST_ACTION TEXT COMMENT '초기대응',
    CODE_BLUE_YN CHAR(1) COMMENT '코드블루 발동여부',
    CODE_BLUE_DT DATETIME COMMENT '코드블루 발동시간',
    CPR_YN CHAR(1) COMMENT 'CPR 시행여부',
    CPR_START_DT DATETIME COMMENT 'CPR 시작시간',
    DR_ARRIVE_DT DATETIME COMMENT '의사도착시간',
    RESULT VARCHAR(50) COMMENT '결과(회복/전원/사망)',
    TRANSFER_HOSP VARCHAR(100) COMMENT '전원병원',
    DEBRIEF_YN CHAR(1) COMMENT '디브리핑 시행여부',
    DEBRIEF_DESC TEXT COMMENT '디브리핑 내용',
    NOTE TEXT COMMENT '비고',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_USER VARCHAR(20),
    PRIMARY KEY (EMG_ID),
    INDEX IDX_TW_EMG_01 (COMP_CD, EMG_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='응급상황 기록';
