-- ═══════════════════════════════════════════════════════════════════════════
-- safeRpt 체크 묶음 보강 2차 — 원본에 있는데 우리 DEF 에 없는 묶음 (2026-09-02, 자동 생성 + 손질)
--   생성 = docs/tools/dfm대조/gen_saferpt_def.js : 원본 dfm 의 TcxCheckBox 를 Hint/라벨로 묶고,
--   ① 우리 묶음과 항목이 반 이상 겹치면 「이미 있음」 ② 하나라도 겹치면 그 묶음에 빠진 항목만 보탬 ③ 안 겹치면 새 묶음(ORGn).
--   MULTI_YN = 원본 .pas 가 Hint 배타면 N(라디오), 아니면 Y. ETC_YN = 「기타」 항목. 점수 칸 라벨·약물별 반복 열은 뺐다.
--   ⚠기존 묶음·항목은 손대지 않는다(작성분의 체크가 그 글자로 저장돼 있다). 재실행 안전.
-- ═══════════════════════════════════════════════════════════════════════════
-- ★1차 자동생성본(09-02 오후, 이름 손질 전 — SELFDIS 「보고부서」·DRUGADRE 「D/E/F」 등)을 먼저 지운다.
--   ORG 묶음은 이 파일만 만들고, 작성분이 쓰기 전에 돌렸으므로 안전하다.
DELETE FROM TBL_QPS_SAFERPT_USE WHERE RPT_GB IN ('PTSAFE','BEDSORE','INFEXP','STAFF','HAZMAT','SWINTAKE','NUTREC','SWVULN','MRFIX','SYSAUTH','SELFDIS','ABUSE','PRIVACY','INFDIS','DRUGADRE') AND GRP_CD LIKE 'ORG%';
DELETE FROM TBL_QPS_SAFERPT_DEF WHERE RPT_GB IN ('PTSAFE','BEDSORE','INFEXP','STAFF','HAZMAT','SWINTAKE','NUTREC','SWVULN','MRFIX','SYSAUTH','SELFDIS','ABUSE','PRIVACY','INFDIS','DRUGADRE') AND GRP_CD LIKE 'ORG%';

INSERT INTO TBL_QPS_SAFERPT_DEF (RPT_GB,GRP_CD,GRP_NM,ITEM_NM,MULTI_YN,ETC_YN,SORT,USE_YN) VALUES
 ('PTSAFE','ORG1','보고부서','병동','N','N',1,'Y'),
 ('PTSAFE','ORG1','보고부서','외래','N','N',2,'Y'),
 ('PTSAFE','ORG1','보고부서','물리/특수부서','N','N',3,'Y'),
 ('PTSAFE','ORG1','보고부서','기타','N','Y',4,'Y'),
 ('PTSAFE','ORG2','관련직원','의사','N','N',1,'Y'),
 ('PTSAFE','ORG2','관련직원','약사','N','N',2,'Y'),
 ('PTSAFE','ORG2','관련직원','간호사','N','N',3,'Y'),
 ('PTSAFE','ORG2','관련직원','의료기사','N','N',4,'Y'),
 ('PTSAFE','ORG2','관련직원','기타','N','Y',5,'Y'),
 ('PTSAFE','ORG3','발생연령','20대','N','N',1,'Y'),
 ('PTSAFE','ORG3','발생연령','30대','N','N',2,'Y'),
 ('PTSAFE','ORG3','발생연령','40대','N','N',3,'Y'),
 ('PTSAFE','ORG3','발생연령','50대','N','N',4,'Y'),
 ('PTSAFE','ORG3','발생연령','60대','N','N',5,'Y'),
 ('PTSAFE','ORG3','발생연령','70대','N','N',6,'Y'),
 ('PTSAFE','ORG3','발생연령','80대','N','N',7,'Y'),
 ('PTSAFE','ORG3','발생연령','90대이상','N','N',8,'Y'),
 ('PTSAFE','ORG4','발생장소','병실','N','N',1,'Y'),
 ('PTSAFE','ORG4','발생장소','화장실','N','N',2,'Y'),
 ('PTSAFE','ORG4','발생장소','로비/복도','N','N',3,'Y'),
 ('PTSAFE','ORG4','발생장소','계단','N','N',4,'Y'),
 ('PTSAFE','ORG4','발생장소','외부','N','N',5,'Y'),
 ('PTSAFE','ORG4','발생장소','목욕실','N','N',6,'Y'),
 ('PTSAFE','ORG4','발생장소','기타','N','Y',7,'Y'),
 ('PTSAFE','DAMAGE','손상종류','외상없음','N','N',7,'Y'),
 ('PTSAFE','DAMAGE','손상종류','타박상','N','N',8,'Y'),
 ('PTSAFE','DAMAGE','손상종류','호흡곤란','N','N',9,'Y'),
 ('PTSAFE','DAMAGE','손상종류','두부손상','N','N',10,'Y'),
 ('PTSAFE','DAMAGE','손상종류','통증','N','N',11,'Y'),
 ('PTSAFE','DAMAGE','손상종류','약물부작용','N','N',12,'Y'),
 ('PTSAFE','DAMAGE','손상종류','사망','N','N',13,'Y'),
 ('PTSAFE','ORG5','발생시간','Day','N','N',1,'Y'),
 ('PTSAFE','ORG5','발생시간','Evening','N','N',2,'Y'),
 ('PTSAFE','ORG5','발생시간','Night','N','N',3,'Y'),
 ('PTSAFE','FALLDRUG','낙상 유발약물','항우울제','N','N',7,'Y'),
 ('PTSAFE','FALLDRUG','낙상 유발약물','항불안제','N','N',8,'Y'),
 ('PTSAFE','FALLDRUG','낙상 유발약물','항정신치료제','N','N',9,'Y'),
 ('PTSAFE','FALLDRUG','낙상 유발약물','최면진정제','N','N',10,'Y'),
 ('PTSAFE','ORG6','낙상유형','침대 사용 시','N','N',1,'Y'),
 ('PTSAFE','ORG6','낙상유형','휠체어 사용 시','N','N',2,'Y'),
 ('PTSAFE','ORG6','낙상유형','의자 사용 시','N','N',3,'Y'),
 ('PTSAFE','ORG6','낙상유형','의료장비 사용 시','N','N',4,'Y'),
 ('PTSAFE','ORG6','낙상유형','기립/보행 시','N','N',5,'Y'),
 ('PTSAFE','ORG6','낙상유형','보조기구 사용 시','N','N',6,'Y'),
 ('PTSAFE','ORG6','낙상유형','기타','N','Y',7,'Y'),
 ('PTSAFE','ORG7','환경 위험요인','침대바퀴 고정 안함','N','N',1,'Y'),
 ('PTSAFE','ORG7','환경 위험요인','보조 난간 내려짐','N','N',2,'Y'),
 ('PTSAFE','ORG7','환경 위험요인','바닥의 물기','N','N',3,'Y'),
 ('PTSAFE','ORG7','환경 위험요인','발에 맞지 않는 신발','N','N',4,'Y'),
 ('PTSAFE','ORG7','환경 위험요인','주변 물건에 걸려 넘어짐','N','N',5,'Y'),
 ('PTSAFE','ORG7','환경 위험요인','기타','N','Y',6,'Y'),
 ('PTSAFE','ORG8','관련 진단','만성질환','N','N',1,'Y'),
 ('PTSAFE','ORG8','관련 진단','골절','N','N',2,'Y'),
 ('PTSAFE','ORG8','관련 진단','치매','N','N',3,'Y'),
 ('PTSAFE','ORG8','관련 진단','뇌졸중','N','N',4,'Y'),
 ('PTSAFE','ORG8','관련 진단','기타','N','Y',5,'Y'),
 ('PTSAFE','ORG9','위험군','고위험군','N','N',1,'Y'),
 ('PTSAFE','ORG9','위험군','저위험군','N','N',2,'Y'),
 ('PTSAFE','ORG9','위험군','정상군','N','N',3,'Y'),
 ('PTSAFE','ORG10','투약오류 (투약 전 발견)','의사처방 오류','N','N',1,'Y'),
 ('PTSAFE','ORG10','투약오류 (투약 전 발견)','약사조제/불출오류','N','N',2,'Y'),
 ('PTSAFE','ORG10','투약오류 (투약 전 발견)','기타','N','Y',3,'Y'),
 ('PTSAFE','ORG11','투약오류 (투약 후 발견)','다른 환자','N','N',1,'Y'),
 ('PTSAFE','ORG11','투약오류 (투약 후 발견)','다른 약품','N','N',2,'Y'),
 ('PTSAFE','ORG11','투약오류 (투약 후 발견)','다른 시간','N','N',3,'Y'),
 ('PTSAFE','ORG11','투약오류 (투약 후 발견)','다른 경로','N','N',4,'Y'),
 ('PTSAFE','ORG11','투약오류 (투약 후 발견)','다른 용량','N','N',5,'Y'),
 ('PTSAFE','ORG11','투약오류 (투약 후 발견)','약물 부작용','N','N',6,'Y'),
 ('PTSAFE','ORG11','투약오류 (투약 후 발견)','투약하지 않아야 할 상황에서의 투약','N','N',7,'Y'),
 ('PTSAFE','ORG11','투약오류 (투약 후 발견)','기타','N','Y',8,'Y'),
 ('BEDSORE','ORG1','발생 후 보고','담당의사','N','N',1,'Y'),
 ('BEDSORE','ORG1','발생 후 보고','수간호사','N','N',2,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','부동','N','N',1,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','감각장애','N','N',2,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','피부마찰 및 쓸림','N','N',3,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','의식불명','N','N',4,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','기저질환','N','N',5,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','영양불량','N','N',6,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','실변/실금','N','N',7,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','혈액학적 불안정','N','N',8,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','신체적제한(신체보호대)','N','N',9,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','기구사용','N','N',10,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','의식상태','N','N',11,'Y'),
 ('BEDSORE','ORG2','욕창 발생 원인','기타','N','Y',12,'Y'),
 ('BEDSORE','ORG3','크기 - 가로','1cm ~ 3cm 미만','N','N',1,'Y'),
 ('BEDSORE','ORG3','크기 - 가로','3cm ~ 5cm 미만','N','N',2,'Y'),
 ('BEDSORE','ORG3','크기 - 가로','5cm ~ 6cm 이상','N','N',3,'Y'),
 ('BEDSORE','ORG4','크기 - 세로','1cm ~ 3cm 미만','N','N',1,'Y'),
 ('BEDSORE','ORG4','크기 - 세로','3cm ~ 5cm 미만','N','N',2,'Y'),
 ('BEDSORE','ORG4','크기 - 세로','5cm ~ 6cm 이상','N','N',3,'Y'),
 ('BEDSORE','ORG5','크기 - 깊이','1cm ~ 3cm 미만','N','N',1,'Y'),
 ('BEDSORE','ORG5','크기 - 깊이','3cm ~ 5cm 미만','N','N',2,'Y'),
 ('BEDSORE','ORG5','크기 - 깊이','5cm ~ 6cm 이상','N','N',3,'Y'),
 ('BEDSORE','PREV','예방간호','압력, 마찰, 응전력을 최소화하기 위한 간호','N','N',7,'Y'),
 ('BEDSORE','PREV','예방간호','통증 관리','N','N',8,'Y'),
 ('BEDSORE','PREV','예방간호','상처 드레싱','N','N',9,'Y'),
 ('BEDSORE','PREV','예방간호','환자 및 보호자 교육','N','N',10,'Y'),
 ('BEDSORE','PREV','예방간호','영양 간호(고단백식이)','N','N',11,'Y'),
 ('BEDSORE','PREV','예방간호','항생제처방','N','N',12,'Y'),
 ('BEDSORE','PREV','예방간호','압력 재분배를 위한 보조기구 사용','N','N',13,'Y'),
 ('BEDSORE','PREV','예방간호','실금/실변 관리','N','N',14,'Y'),
 ('INFEXP','ORG1','사고유형','주사침자상','N','N',1,'Y'),
 ('INFEXP','ORG1','사고유형','혈액 및 체액','N','N',2,'Y'),
 ('INFEXP','ORG1','사고유형','결핵','N','N',3,'Y'),
 ('INFEXP','ORG1','사고유형','기타','N','Y',4,'Y'),
 ('INFEXP','ORG2','사고경위','수술 및 시술 중','N','N',1,'Y'),
 ('INFEXP','ORG2','사고경위','주사처치 중','N','N',2,'Y'),
 ('INFEXP','ORG2','사고경위','정맥혈채취 중','N','N',3,'Y'),
 ('INFEXP','ORG2','사고경위','동맥혈채취 중','N','N',4,'Y'),
 ('INFEXP','ORG2','사고경위','Recapping','N','N',5,'Y'),
 ('INFEXP','ORG2','사고경위','분리수거 중','N','N',6,'Y'),
 ('INFEXP','ORG2','사고경위','기타','N','Y',7,'Y'),
 ('STAFF','ACCTYPE','사고유형','열상','N','N',8,'Y'),
 ('STAFF','ACCTYPE','사고유형','타박상','N','N',9,'Y'),
 ('STAFF','ACCTYPE','사고유형','화상','N','N',10,'Y'),
 ('STAFF','ACCTYPE','사고유형','눈,피부에 접촉','N','N',11,'Y'),
 ('STAFF','ACCTYPE','사고유형','흡입','N','N',12,'Y'),
 ('STAFF','ACCTYPE','사고유형','산업재해','N','N',13,'Y'),
 ('STAFF','ACCTYPE','사고유형','폭언','N','N',14,'Y'),
 ('STAFF','ACCTYPE','사고유형','욕설','N','N',15,'Y'),
 ('STAFF','ORG1','추후관리','지속적인 치료가 필요','N','N',1,'Y'),
 ('STAFF','ORG1','추후관리','치료후 후유증 없이 치료됨','N','N',2,'Y'),
 ('STAFF','ORG1','추후관리','특별한 이상 없음','N','N',3,'Y'),
 ('STAFF','ORG1','추후관리','추후 관찰 필요','N','N',4,'Y'),
 ('STAFF','ORG1','추후관리','기타','N','Y',5,'Y'),
 ('HAZMAT','HZACT','조치사항','조치하지 않음','N','N',7,'Y'),
 ('HAZMAT','HZACT','조치사항','노출부위 세척','N','N',8,'Y'),
 ('HAZMAT','HZACT','조치사항','조치 필요 없음','N','N',9,'Y'),
 ('HAZMAT','ORG1','Spill kit 사용여부','사용','N','N',1,'Y'),
 ('HAZMAT','ORG1','Spill kit 사용여부','미사용','N','N',2,'Y'),
 ('HAZMAT','ORG1','Spill kit 사용여부','모름','N','N',3,'Y'),
 ('SWINTAKE','ORG1','결혼상태','미혼','N','N',1,'Y'),
 ('SWINTAKE','ORG1','결혼상태','기혼','N','N',2,'Y'),
 ('SWINTAKE','ORG1','결혼상태','이혼','N','N',3,'Y'),
 ('SWINTAKE','ORG1','결혼상태','별거','N','N',4,'Y'),
 ('SWINTAKE','ORG1','결혼상태','사별','N','N',5,'Y'),
 ('SWINTAKE','ORG1','결혼상태','동거','N','N',6,'Y'),
 ('SWINTAKE','ORG2','주거상태','자가','N','N',1,'Y'),
 ('SWINTAKE','ORG2','주거상태','전세','N','N',2,'Y'),
 ('SWINTAKE','ORG2','주거상태','월세','N','N',3,'Y'),
 ('SWINTAKE','ORG2','주거상태','기타','N','Y',4,'Y'),
 ('NUTREC','ORG1','저작상태','부드러운 것은 씹을 수 있다.','Y','N',1,'Y'),
 ('NUTREC','ORG1','저작상태','씹을 수 없다.','Y','N',2,'Y'),
 ('NUTREC','ORG2','연하상태','무엇이든 삼킬 수 있다.','Y','N',1,'Y'),
 ('NUTREC','ORG2','연하상태','삼킬 수 없다.','Y','N',2,'Y'),
 ('NUTREC','ORG2','연하상태','사래 들린다.','Y','N',3,'Y'),
 ('SWVULN','ORG1','접수일시','오전','N','N',1,'Y'),
 ('SWVULN','ORG1','접수일시','오후','N','N',2,'Y'),
 ('SWVULN','ORG2','상담일시','오전','N','N',1,'Y'),
 ('SWVULN','ORG2','상담일시','오후','N','N',2,'Y'),
 ('SWVULN','ORG3','행정절차','본원에서 자체 해결','N','N',1,'Y'),
 ('SWVULN','ORG3','행정절차','응급 시 (타 병원·112신고)','N','N',2,'Y'),
 ('SWVULN','ORG3','행정절차','타기관 연계 (노인학대 예방센터·한국 농아인 협회)','N','N',3,'Y'),
 ('MRFIX','ORG1','정정 요구 처리','승낙','N','N',1,'Y'),
 ('MRFIX','ORG1','정정 요구 처리','거절','N','N',2,'Y'),
 ('MRFIX','ORG2','문서 첨부 여부','첨부','N','N',1,'Y'),
 ('MRFIX','ORG2','문서 첨부 여부','첨부하지 않음','N','N',2,'Y'),
 ('SYSAUTH','ORG1','신청 구분','신규','N','N',1,'Y'),
 ('SYSAUTH','ORG1','신청 구분','연장','N','N',2,'Y'),
 ('SYSAUTH','ORG2','요청 권한','작성','N','N',1,'Y'),
 ('SYSAUTH','ORG2','요청 권한','조회','N','N',2,'Y'),
 ('SYSAUTH','ORG2','요청 권한','기타','N','Y',3,'Y'),
 ('SELFDIS','ORG1','대리인 서명사유','환자의 신체, 정신적 장애로 인하여 약정내용에 대하여 이해하지 못함.','Y','N',1,'Y'),
 ('SELFDIS','ORG1','대리인 서명사유','설명하는 것이 환자의 심신에 중대한 나쁜 영향을 미칠 것이 명백함.','Y','N',2,'Y'),
 ('SELFDIS','ORG1','대리인 서명사유','환자 본인이 승낙에 관한 권한을 특정인에 위임','Y','N',3,'Y'),
 ('SELFDIS','ORG1','대리인 서명사유','기타','Y','Y',4,'Y'),
 ('PRIVACY','ORG1','요청 항목','1. 환자상태','N','N',1,'Y'),
 ('PRIVACY','ORG1','요청 항목','2. 면회사절','N','N',2,'Y'),
 ('PRIVACY','ORG1','요청 항목','3. 병실공개금지','N','N',3,'Y'),
 ('PRIVACY','ORG1','요청 항목','4. 진료비안내금지','N','N',4,'Y'),
 ('PRIVACY','ORG1','요청 항목','5. 기타요청사항','N','Y',5,'Y'),
 ('PRIVACY','ORG2','요청 여부','요청','N','N',1,'Y'),
 ('PRIVACY','ORG2','요청 여부','요청안함','N','N',2,'Y'),
 ('DRUGADRE','ORG1','부작용 경과','소실','N','N',1,'Y'),
 ('DRUGADRE','ORG1','부작용 경과','지속','N','N',2,'Y'),
 ('DRUGADRE','ORG1','부작용 경과','회복됨','N','N',3,'Y'),
 ('DRUGADRE','ORG1','부작용 경과','회복중','N','N',4,'Y'),
 ('DRUGADRE','ORG1','부작용 경과','모름','N','N',5,'Y')
ON DUPLICATE KEY UPDATE GRP_NM=VALUES(GRP_NM), MULTI_YN=VALUES(MULTI_YN), ETC_YN=VALUES(ETC_YN), SORT=VALUES(SORT), USE_YN='Y';

INSERT INTO TBL_QPS_SAFERPT_USE (RPT_GB,GRP_CD,SORT,USE_YN) VALUES
 ('PTSAFE','ORG1',11,'Y'),
 ('PTSAFE','ORG2',12,'Y'),
 ('PTSAFE','ORG3',13,'Y'),
 ('PTSAFE','ORG4',14,'Y'),
 ('PTSAFE','ORG5',15,'Y'),
 ('PTSAFE','ORG6',16,'Y'),
 ('PTSAFE','ORG7',17,'Y'),
 ('PTSAFE','ORG8',18,'Y'),
 ('PTSAFE','ORG9',19,'Y'),
 ('PTSAFE','ORG10',20,'Y'),
 ('PTSAFE','ORG11',21,'Y'),
 ('BEDSORE','ORG1',4,'Y'),
 ('BEDSORE','ORG2',5,'Y'),
 ('BEDSORE','ORG3',6,'Y'),
 ('BEDSORE','ORG4',7,'Y'),
 ('BEDSORE','ORG5',8,'Y'),
 ('INFEXP','ORG1',5,'Y'),
 ('INFEXP','ORG2',6,'Y'),
 ('STAFF','ORG1',4,'Y'),
 ('HAZMAT','ORG1',6,'Y'),
 ('SWINTAKE','ORG1',3,'Y'),
 ('SWINTAKE','ORG2',4,'Y'),
 ('NUTREC','ORG1',7,'Y'),
 ('NUTREC','ORG2',8,'Y'),
 ('SWVULN','ORG1',3,'Y'),
 ('SWVULN','ORG2',4,'Y'),
 ('SWVULN','ORG3',5,'Y'),
 ('MRFIX','ORG1',3,'Y'),
 ('MRFIX','ORG2',4,'Y'),
 ('SYSAUTH','ORG1',2,'Y'),
 ('SYSAUTH','ORG2',3,'Y'),
 ('SELFDIS','ORG1',2,'Y'),
 ('PRIVACY','ORG1',3,'Y'),
 ('PRIVACY','ORG2',4,'Y'),
 ('DRUGADRE','ORG1',8,'Y')
ON DUPLICATE KEY UPDATE SORT=VALUES(SORT), USE_YN='Y';

-- 확인
SELECT RPT_GB, GRP_CD, GRP_NM, COUNT(*) n FROM TBL_QPS_SAFERPT_DEF WHERE RPT_GB IN ('PTSAFE','BEDSORE','INFEXP','STAFF','HAZMAT','SWINTAKE','NUTREC','SWVULN','MRFIX','SYSAUTH','SELFDIS','ABUSE','PRIVACY','INFDIS','DRUGADRE') AND USE_YN='Y' GROUP BY RPT_GB, GRP_CD, GRP_NM ORDER BY RPT_GB, GRP_CD;
